# Generated for AI Training System

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0060_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainingexample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('normalized_text', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(max_length=50, choices=[('buy_property', 'Buy Property'), ('sell_property', 'Sell Property'), ('join_agent', 'Join Agent'), ('find_job', 'Find Job'), ('travel', 'Travel'), ('find_hotel', 'Find Hotel'), ('find_service', 'Find Service'), ('construction', 'Construction'), ('auction', 'Auction'), ('find_resort', 'Find Resort'), ('find_product', 'Find Product'), ('general_question', 'General Question'), ('support', 'Support'), ('unknown', 'Unknown')])),
                ('confidence', models.FloatField(default=0.0)),
                ('entities', models.JSONField(default=dict, blank=True)),
                ('dataset_type', models.CharField(max_length=50, choices=[('initial', 'Initial Dataset'), ('user_generated', 'User Generated'), ('augmented', 'Data Augmented'), ('expert_curated', 'Expert Curated')], default='user_generated')),
                ('source', models.CharField(max_length=100, blank=True)),
                ('conversation_id', models.CharField(max_length=100, blank=True)),
                ('original_message', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user', related_name='reviewed_examples')),
                ('reviewed_at', models.DateTimeField(null=True, blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(null=True, blank=True)),
                ('is_augmented', models.BooleanField(default=False)),
                ('parent_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='augmented_examples', to='properties.trainingexample')),
                ('augmentation_method', models.CharField(max_length=50, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_training_examples',
            },
        ),
        migrations.CreateModel(
            name='userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('feedback_type', models.CharField(max_length=20, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')])),
                ('feedback_context', models.CharField(max_length=50, choices=[('search_results', 'Search Results'), ('response_quality', 'Response Quality'), ('clarification', 'Clarification'), ('suggestion', 'Suggestion'), ('general', 'General')], default='general')),
                ('detected_intent', models.CharField(max_length=50, blank=True)),
                ('detected_entities', models.JSONField(default=dict, blank=True)),
                ('confidence', models.FloatField(null=True, blank=True)),
                ('user_clarification', models.TextField(blank=True)),
                ('rating', models.IntegerField(null=True, blank=True)),
                ('results_shown', models.JSONField(default=list, blank=True)),
                ('selected_result', models.JSONField(null=True, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('session_data', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_user_feedback',
            },
        ),
        migrations.CreateModel(
            name='unknownquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('conversation_id', models.CharField(max_length=100)),
                ('attempted_intent', models.CharField(max_length=50, blank=True)),
                ('attempted_entities', models.JSONField(default=dict, blank=True)),
                ('confidence', models.FloatField(null=True, blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_intent', models.CharField(max_length=50, blank=True)),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('resolved_at', models.DateTimeField(null=True, blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=1)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_unknown_queries',
            },
        ),
        migrations.CreateModel(
            name='modelversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('training_dataset_version', models.CharField(max_length=50)),
                ('training_date', models.DateTimeField()),
                ('training_duration', models.DurationField(null=True, blank=True)),
                ('training_config', models.JSONField(default=dict, blank=True)),
                ('model_file_path', models.CharField(max_length=255, blank=True)),
                ('model_size_mb', models.FloatField(null=True, blank=True)),
                ('model_checksum', models.CharField(max_length=64, blank=True)),
                ('accuracy', models.FloatField(null=True, blank=True)),
                ('precision', models.FloatField(null=True, blank=True)),
                ('recall', models.FloatField(null=True, blank=True)),
                ('f1_score', models.FloatField(null=True, blank=True)),
                ('evaluation_dataset_version', models.CharField(max_length=50, blank=True)),
                ('evaluation_date', models.DateTimeField(null=True, blank=True)),
                ('status', models.CharField(max_length=20, choices=[('training', 'Training'), ('testing', 'Testing'), ('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='training')),
                ('deployed_at', models.DateTimeField(null=True, blank=True)),
                ('deployed_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('avg_response_time_ms', models.FloatField(null=True, blank=True)),
                ('success_rate', models.FloatField(null=True, blank=True)),
                ('user_satisfaction', models.FloatField(null=True, blank=True)),
                ('can_rollback', models.BooleanField(default=True)),
                ('rollback_deadline', models.DateTimeField(null=True, blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('known_issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_model_versions',
            },
        ),
        migrations.CreateModel(
            name='modelevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='properties.modelversion')),
                ('evaluation_dataset', models.CharField(max_length=50)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('test_type', models.CharField(max_length=50)),
                ('total_tests', models.IntegerField()),
                ('passed_tests', models.IntegerField()),
                ('failed_tests', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField(null=True, blank=True)),
                ('recall', models.FloatField(null=True, blank=True)),
                ('f1_score', models.FloatField(null=True, blank=True)),
                ('detailed_results', models.JSONField(default=dict, blank=True)),
                ('confusion_matrix', models.JSONField(default=dict, blank=True)),
                ('compared_to_version', models.CharField(max_length=50, blank=True)),
                ('accuracy_delta', models.FloatField(null=True, blank=True)),
                ('improvement', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ai_model_evaluations',
            },
        ),
        migrations.CreateModel(
            name='searchanalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('normalized_query', models.TextField(blank=True, null=True)),
                ('detected_intent', models.CharField(max_length=50)),
                ('detected_entities', models.JSONField(default=dict, blank=True)),
                ('confidence', models.FloatField()),
                ('search_params', models.JSONField(default=dict, blank=True)),
                ('results_count', models.IntegerField()),
                ('results_shown', models.JSONField(default=list, blank=True)),
                ('selected_result', models.JSONField(null=True, blank=True)),
                ('user_feedback', models.CharField(max_length=20, blank=True)),
                ('clicked_results', models.JSONField(default=list, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('session_id', models.CharField(max_length=100, blank=True)),
                ('search_duration_ms', models.FloatField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_search_analytics',
            },
        ),
        migrations.CreateModel(
            name='conversationlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True, blank=True)),
                ('duration_seconds', models.DurationField(null=True, blank=True)),
                ('messages', models.JSONField(default=list)),
                ('final_intent', models.CharField(max_length=50, blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True)),
                ('user_satisfaction', models.IntegerField(null=True, blank=True)),
                ('agent_performance_score', models.FloatField(null=True, blank=True)),
                ('session_data', models.JSONField(default=dict, blank=True)),
            ],
            options={
                'db_table': 'ai_conversation_logs',
            },
        ),
        migrations.CreateModel(
            name='knowledgebaseentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50, choices=[('faq', 'FAQ'), ('policy', 'Policy'), ('guide', 'Guide'), ('service', 'Service'), ('general', 'General')])),
                ('content', models.TextField()),
                ('keywords', models.JSONField(default=list, blank=True)),
                ('language', models.CharField(max_length=10, default='ar')),
                ('priority', models.IntegerField(default=1)),
                ('related_urls', models.JSONField(default=list, blank=True)),
                ('related_sections', models.JSONField(default=list, blank=True)),
                ('version', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('status', models.CharField(max_length=20, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft')),
                ('published_at', models.DateTimeField(null=True, blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('embedding_vector', models.JSONField(null=True, blank=True)),
                ('embedding_model', models.CharField(max_length=100, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='toolusagelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(max_length=100)),
                ('input_data', models.JSONField(default=dict, blank=True)),
                ('success', models.BooleanField()),
                ('output_data', models.JSONField(default=dict, blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField()),
                ('intent', models.CharField(max_length=50, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='auth.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_tool_usage_log',
            },
        ),
    ]