# Generated by Django 6.0.6 on 2026-07-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0113_property_expiry_date_property_frozen_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('company_type', models.CharField(choices=[('tourism', 'سياحة'), ('hajj_umrah', 'حج وعمرة'), ('visa_services', 'خدمات الفيزا'), ('general', 'عامة')], max_length=20, verbose_name='نوع الشركة')),
                ('travel_types', models.JSONField(blank=True, null=True, verbose_name='أنواع السفر')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('logo', models.ImageField(blank=True, upload_to='travel_companies/logos/', verbose_name='الشعار')),
                ('cover_image', models.ImageField(blank=True, upload_to='travel_companies/covers/', verbose_name='صورة الغلاف')),
                ('governorate', models.CharField(blank=True, max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='التقييم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_companies', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شركة سفر',
                'verbose_name_plural': 'شركات السفر',
            },
        ),
        migrations.CreateModel(
            name='TravelCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_companies/images/', verbose_name='الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.travelcompany', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'صورة شركة السفر',
                'verbose_name_plural': 'صور شركات السفر',
            },
        ),
        migrations.CreateModel(
            name='TravelCompanyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='travel_companies/videos/', verbose_name='الفيديو')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.travelcompany', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فيديو شركة السفر',
                'verbose_name_plural': 'فيديوهات شركات السفر',
            },
        ),
        migrations.CreateModel(
            name='ResortInsideIraq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('resort_type', models.CharField(choices=[('beach', 'شاطئي'), ('mountain', 'جبلي'), ('desert', 'صحراوي'), ('lake', 'بحيرة'), ('spa', 'سبا'), ('family', 'عائلي'), ('luxury', 'فاخر'), ('adventure', 'مغامرة'), ('eco', 'بيئي'), ('cultural', 'ثقافي')], max_length=20, verbose_name='نوع المنتجع')),
                ('governorate', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لليلة')),
                ('currency', models.CharField(default='IQD', max_length=3, verbose_name='العملة')),
                ('min_guests', models.IntegerField(default=1, verbose_name='الحد الأدنى للضيوف')),
                ('max_guests', models.IntegerField(default=10, verbose_name='الحد الأقصى للضيوف')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='واي فاي')),
                ('has_pool', models.BooleanField(default=False, verbose_name='مسبح')),
                ('has_parking', models.BooleanField(default=False, verbose_name='موقف سيارات')),
                ('has_playground', models.BooleanField(default=False, verbose_name='ملعب أطفال')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('has_bbq', models.BooleanField(default=False, verbose_name='مكان شواء')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='التقييم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resorts_inside_iraq', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'منتجع داخل العراق',
                'verbose_name_plural': 'منتجعات داخل العراق',
            },
        ),
        migrations.CreateModel(
            name='ResortImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resorts/images/', verbose_name='الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'صورة المنتجع',
                'verbose_name_plural': 'صور المنتجعات',
            },
        ),
        migrations.CreateModel(
            name='ResortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='resorts/videos/', verbose_name='الفيديو')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'فيديو المنتجع',
                'verbose_name_plural': 'فيديوهات المنتجعات',
            },
        ),
        migrations.CreateModel(
            name='ResortOutsideIraq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('resort_type', models.CharField(choices=[('beach', 'شاطئي'), ('mountain', 'جبلي'), ('desert', 'صحراوي'), ('lake', 'بحيرة'), ('spa', 'سبا'), ('family', 'عائلي'), ('luxury', 'فاخر'), ('adventure', 'مغامرة'), ('eco', 'بيئي'), ('cultural', 'ثقافي')], max_length=20, verbose_name='نوع المنتجع')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resorts_outside_iraq', to='properties.country', verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر لليلة')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='العملة')),
                ('min_guests', models.IntegerField(default=1, verbose_name='الحد الأدنى للضيوف')),
                ('max_guests', models.IntegerField(default=10, verbose_name='الحد الأقصى للضيوف')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='واي فاي')),
                ('has_pool', models.BooleanField(default=False, verbose_name='مسبح')),
                ('has_parking', models.BooleanField(default=False, verbose_name='موقف سيارات')),
                ('has_playground', models.BooleanField(default=False, verbose_name='ملعب أطفال')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('has_bbq', models.BooleanField(default=False, verbose_name='مكان شواء')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='التقييم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resorts_outside_iraq', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'منتجع خارج العراق',
                'verbose_name_plural': 'منتجعات خارج العراق',
            },
        ),
    ]
