# Generated by Django 6.0.6 on 2026-07-14 15:20

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0130_add_is_featured_to_resortoutside'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resortinsideiraq',
            options={'ordering': ['-is_featured', '-rating', '-created_at'], 'verbose_name': 'منتجع داخل العراق', 'verbose_name_plural': 'المنتجعات داخل العراق'},
        ),
        migrations.AlterModelOptions(
            name='resortoutsideiraq',
            options={'ordering': ['-is_featured', '-rating', '-created_at'], 'verbose_name': 'منتجع خارج العراق', 'verbose_name_plural': 'المنتجعات خارج العراق'},
        ),
        migrations.AlterModelOptions(
            name='travelcompany',
            options={'ordering': ['-is_featured', '-rating', '-created_at'], 'verbose_name': 'شركة سفر', 'verbose_name_plural': 'شركات السفر'},
        ),
        migrations.AlterModelOptions(
            name='travelcompanyimage',
            options={'ordering': ['order'], 'verbose_name': 'صورة شركة سفر', 'verbose_name_plural': 'صور شركات السفر'},
        ),
        migrations.AlterModelOptions(
            name='travelcompanyvideo',
            options={'ordering': ['order'], 'verbose_name': 'فيديو شركة سفر', 'verbose_name_plural': 'فيديوهات شركات السفر'},
        ),
        # Skip RemoveField operations for fields that don't exist in the models
        # These fields were not added in 0117, so we skip their removal
        migrations.AddField(
            model_name='travelcompanyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='travelcompanyvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='travelcompanyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=properties.models.travel_company_image_path, verbose_name='صورة مصغرة'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='address',
            field=models.CharField(max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=properties.models.resort_image_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='currency',
            field=models.CharField(default='IQD', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='description',
            field=models.TextField(verbose_name='وصف المنتجع'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='governorate',
            field=models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر لليلة'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='resortinsideiraq',
            name='resort_type',
            field=models.CharField(choices=[('beach', 'شاطئي'), ('mountain', 'جبلي'), ('desert', 'صحراوي'), ('lake', 'بحيرة'), ('spa', 'سبا'), ('family', 'عائلي'), ('luxury', 'فاخر'), ('adventure', 'مغامرة'), ('eco', 'بيئي'), ('cultural', 'ثقافي')], max_length=50, verbose_name='نوع المنتجع'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='address',
            field=models.CharField(max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.country', verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=properties.models.resort_image_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='description',
            field=models.TextField(verbose_name='وصف المنتجع'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر لليلة'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='resortoutsideiraq',
            name='resort_type',
            field=models.CharField(choices=[('beach', 'شاطئي'), ('mountain', 'جبلي'), ('desert', 'صحراوي'), ('lake', 'بحيرة'), ('spa', 'سبا'), ('family', 'عائلي'), ('luxury', 'فاخر'), ('adventure', 'مغامرة'), ('eco', 'بيئي'), ('cultural', 'ثقافي')], max_length=50, verbose_name='نوع المنتجع'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='address',
            field=models.CharField(max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='company_type',
            field=models.CharField(choices=[('tourism', 'سياحة'), ('hajj_umrah', 'حج وعمرة'), ('business', 'أعمال'), ('adventure', 'مغامرة'), ('medical', 'سياحة علاجية'), ('educational', 'سياحة تعليمية')], max_length=50, verbose_name='نوع الشركة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=properties.models.travel_company_image_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='governorate',
            field=models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='logo',
            field=models.ImageField(blank=True, upload_to=properties.models.travel_company_image_path, verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='travel_types',
            field=models.JSONField(default=list, verbose_name='أنواع السفر المدعومة'),
        ),
        migrations.AlterField(
            model_name='travelcompanyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.travel_company_image_path, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='travelcompanyvideo',
            name='video',
            field=models.FileField(upload_to=properties.models.travel_company_video_path, verbose_name='الفيديو'),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, upload_to=properties.models.job_image_path, verbose_name='شعار الشركة')),
                ('company_website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('job_title', models.CharField(max_length=200, verbose_name='اسم الوظيفة')),
                ('job_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('freelance', 'عمل حر'), ('remote', 'عن بعد'), ('internship', 'تدريب'), ('contract', 'عقد مؤقت')], max_length=20, verbose_name='نوع العمل')),
                ('field', models.CharField(max_length=100, verbose_name='المجال/الحقل')),
                ('location_type', models.CharField(choices=[('inside_iraq', 'داخل العراق'), ('outside_iraq', 'خارج العراق')], default='inside_iraq', max_length=20, verbose_name='نوع الموقع')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('salary_range', models.CharField(choices=[('any', 'أي راتب'), ('under_500k', 'أقل من 500 ألف'), ('500k_1m', '500 ألف - مليون'), ('1m_2m', 'مليون - مليوني دينار'), ('over_2m', 'أكثر من مليوني دينار'), ('negotiable', 'قابل للتفاوض')], max_length=20, verbose_name='الراتب')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الحد الأدنى للراتب')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الحد الأقصى للراتب')),
                ('education', models.CharField(choices=[('none', 'بدون شهادة'), ('high_school', 'إعدادية'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المؤهل المطلوب')),
                ('experience', models.CharField(choices=[('none', 'بدون خبرة'), ('1_year', 'سنة'), ('2_years', 'سنتان'), ('3_years', '3 سنوات'), ('5_years', '5 سنوات'), ('10_plus', 'أكثر من 10 سنوات')], max_length=20, verbose_name='الخبرة المطلوبة')),
                ('skills', models.TextField(blank=True, verbose_name='المهارات المطلوبة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('responsibilities', models.TextField(blank=True, verbose_name='المسؤوليات')),
                ('benefits', models.TextField(blank=True, verbose_name='المزايا')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('cover_image', models.ImageField(blank=True, upload_to=properties.models.job_image_path, verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='عدد المتقدمين')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.country', verbose_name='الدولة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'فرصة عمل',
                'verbose_name_plural': 'فرص العمل',
                'ordering': ['-is_featured', '-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.job_image_path, verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.jobposting', verbose_name='فرصة العمل')),
            ],
            options={
                'verbose_name': 'صورة فرصة عمل',
                'verbose_name_plural': 'صور فرص العمل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=properties.models.job_video_path, verbose_name='الفيديو')),
                ('thumbnail', models.ImageField(blank=True, upload_to=properties.models.job_image_path, verbose_name='صورة مصغرة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.jobposting', verbose_name='فرصة العمل')),
            ],
            options={
                'verbose_name': 'فيديو فرصة عمل',
                'verbose_name_plural': 'فيديوهات فرص العمل',
                'ordering': ['order'],
            },
        ),
    ]
