# Generated by Django 6.0.6 on 2026-07-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0131_alter_resortinsideiraq_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانطلاق'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='travel_scope',
            field=models.CharField(choices=[('inside_iraq', 'داخل العراق'), ('outside_iraq', 'خارج العراق'), ('both', 'كلاهما')], default='inside_iraq', max_length=20, verbose_name='نطاق السفر'),
        ),
    ]
