# Generated by Django 6.0.6 on 2026-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0132_travelcompany_departure_time_travelcompany_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dallalsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('basic', 'دلال عادي'), ('premium', 'دلال مميز'), ('travel_company', 'شركة سفر'), ('job_posting', 'نشر وظيفة')], max_length=20, verbose_name='نوع الاشتراك'),
        ),
    ]
