# Generated by Django 6.0.6 on 2026-07-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0133_alter_dallalsubscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='نوع الاشتراك'),
        ),
        migrations.AlterField(
            model_name='subscriptionrenewalrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.advancedsubscriptionplan', verbose_name='الخطة المطلوبة'),
        ),
    ]
