# Generated by Django 6.0.6 on 2026-07-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0134_subscriptionrenewalrequest_subscription_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingrequestsubscription',
            options={'verbose_name': 'اشتراك طلبات بناء', 'verbose_name_plural': 'اشتراكات طلبات الباء'},
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم النسخة')),
                ('backup_type', models.CharField(choices=[('full', 'نسخة كاملة'), ('database', 'قاعدة البيانات'), ('files', 'الملفات')], max_length=20, verbose_name='نوع النسخة')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الحجم (MB)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
    ]
