# Generated by Django 5.2.17 on 2026-08-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0136_property_region_and_notification_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف وظائف',
                'verbose_name_plural': 'تصنيفات الوظائف',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='الرابط')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, upload_to='jobs/companies/', verbose_name='شعار الشركة')),
                ('company_description', models.TextField(blank=True, verbose_name='وصف الشركة')),
                ('job_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('freelance', 'عمل حر'), ('internship', 'تدريب')], default='full_time', max_length=20, verbose_name='نوع الوظيفة')),
                ('experience_level', models.CharField(choices=[('entry', 'مبتدئ'), ('junior', 'جونيور'), ('mid', 'متوسط'), ('senior', 'خبير'), ('lead', 'قائد فريق'), ('manager', 'مدير')], default='mid', max_length=20, verbose_name='مستوى الخبرة')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('is_remote', models.BooleanField(default=False, verbose_name='عمل عن بعد')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للراتب')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للراتب')),
                ('salary_currency', models.CharField(default='IQD', max_length=3, verbose_name='عملة الراتب')),
                ('salary_period', models.CharField(choices=[('hourly', 'بالساعة'), ('daily', 'يومي'), ('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='فترة الراتب')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='الراتب قابل للتفاوض')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('responsibilities', models.TextField(verbose_name='المسؤوليات')),
                ('benefits', models.TextField(blank=True, verbose_name='المزايا')),
                ('skills', models.TextField(verbose_name='المهارات المطلوبة')),
                ('contact_name', models.CharField(max_length=100, verbose_name='اسم جهة الاتصال')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('closed', 'مغلق'), ('filled', 'مشغول')], default='draft', max_length=20, verbose_name='الحالة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الإعلان')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('applications_count', models.IntegerField(default=0, verbose_name='عدد الطلبات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL, verbose_name='تم النشر بواسطة')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='properties.jobcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'فرصة عمل',
                'verbose_name_plural': 'فرص العمل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('current_position', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي الحالي')),
                ('current_company', models.CharField(blank=True, max_length=100, verbose_name='الشركة الحالية')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('cv_file', models.FileField(upload_to='jobs/cvs/', verbose_name='ملف السيرة الذاتية')),
                ('cover_letter', models.TextField(blank=True, verbose_name='رسالة التقديم')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='رابط الأعمال السابقة')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب المتوقع')),
                ('available_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوفر')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'مدرج في القائمة المختصرة'), ('interview', 'مقابلة شخصية'), ('offered', 'تم تقديم عرض'), ('accepted', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('recruiter_notes', models.TextField(blank=True, verbose_name='ملاحظات المسؤول')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='المتقدم')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.job', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
