# Generated by Django 5.2.17 on 2026-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0137_jobcategory_job_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('inside_iraq', 'داخل العراق'), ('outside_iraq', 'خارج العراق')], default='inside_iraq', max_length=20, verbose_name='نوع الموقع'),
        ),
        migrations.AddField(
            model_name='job',
            name='outside_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة (خارج العراق)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='governorate',
            field=models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=50, verbose_name='المحافظة'),
        ),
    ]
