# Generated by Django 5.2.17 on 2026-08-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0138_job_country_job_location_type_job_outside_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, choices=[('uae', 'الإمارات العربية المتحدة'), ('saudi', 'السعودية'), ('kuwait', 'الكويت'), ('qatar', 'قطر'), ('bahrain', 'البحرين'), ('oman', 'عمان'), ('jordan', 'الأردن'), ('egypt', 'مصر'), ('turkey', 'تركيا'), ('iran', 'إيران'), ('syria', 'سوريا'), ('lebanon', 'لبنان'), ('other', 'أخرى')], max_length=50, verbose_name='الدولة'),
        ),
    ]
