# Generated by Django 5.2.17 on 2026-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0139_alter_job_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='other_country_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الدولة الأخرى'),
        ),
    ]
