# Generated by Django 5.2.17 on 2026-08-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0140_job_other_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_image',
            field=models.ImageField(blank=True, upload_to='jobs/workplace/', verbose_name='صورة موقع العمل'),
        ),
    ]
