# Generated by Django 5.2.17 on 2026-08-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0141_job_additional_images_job_latitude_job_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posting_duration_days',
            field=models.IntegerField(default=30, verbose_name='مدة النشر بالأيام'),
        ),
    ]
