# Generated by Django 5.2.17 on 2026-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0142_job_posting_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='عادية'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='عادية'),
        ),
    ]
