# Generated by Django 5.2.17 on 2026-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0143_alter_job_is_urgent_alter_jobposting_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_video',
            field=models.FileField(blank=True, help_text='رفع فيديو تعريفي عن الوظيفة', null=True, upload_to='jobs/videos/', verbose_name='فيديو الوظيفة'),
        ),
        migrations.AddField(
            model_name='job',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو من YouTube أو منصة أخرى', verbose_name='رابط فيديو خارجي'),
        ),
    ]
