# Generated by Django 5.2.17 on 2026-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0144_job_job_video_job_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='display_method',
            field=models.CharField(choices=[('homepage_only', 'الصفحة الرئيسية فقط'), ('standalone_only', 'الصفحة المستقلة فقط'), ('both', 'الاثنين معاً')], default='both', max_length=20, verbose_name='طريقة العرض'),
        ),
    ]
