# Generated by Django 5.2.17 on 2026-08-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0145_job_display_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='display_method',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_video',
        ),
        migrations.RemoveField(
            model_name='job',
            name='video_url',
        ),
        migrations.AddField(
            model_name='job',
            name='display_mode',
            field=models.CharField(choices=[('main_only', 'الصفحة الرئيسية فقط'), ('standalone_only', 'الصفحة المستقلة فقط'), ('both', 'الاثنين معاً')], default='both', help_text='اختر أين تظهر وظيفتك', max_length=20, verbose_name='طريقة عرض الصفحة'),
        ),
    ]
