# Generated by Django 5.2.17 on 2026-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0146_remove_job_display_method_remove_job_job_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='display_mode',
        ),
        migrations.AddField(
            model_name='job',
            name='education_requirement',
            field=models.CharField(choices=[('high_school', 'شهادة ثانوية'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('not_required', 'غير مطلوب')], default='not_required', max_length=20, verbose_name='الحد الأدنى للتعليم'),
        ),
        migrations.AddField(
            model_name='job',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للاتصال'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنوات الخبرة المطلوبة'),
        ),
        migrations.AddField(
            model_name='job',
            name='external_application_url',
            field=models.URLField(blank=True, help_text='إذا كان التقديم عبر موقع آخر', verbose_name='رابط التقديم الخارجي'),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_requirement',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('both', 'الجنسين'), ('not_specified', 'غير محدد')], default='not_specified', max_length=20, verbose_name='الجنس المطلوب'),
        ),
        migrations.AddField(
            model_name='job',
            name='has_health_insurance',
            field=models.BooleanField(default=False, verbose_name='تأمين صحي'),
        ),
        migrations.AddField(
            model_name='job',
            name='has_housing_allowance',
            field=models.BooleanField(default=False, verbose_name='بدلة سكن'),
        ),
        migrations.AddField(
            model_name='job',
            name='has_transport_allowance',
            field=models.BooleanField(default=False, verbose_name='بدلة نقل'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('both', 'عربي وإنجليزي')], default='arabic', max_length=20, verbose_name='لغة الوظيفة'),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_positions',
            field=models.IntegerField(default=1, verbose_name='عدد الموظفين المطلوبين'),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف للاتصال'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بدء العمل'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_environment',
            field=models.CharField(choices=[('onsite', 'في الموقع'), ('remote', 'عن بعد'), ('hybrid', 'هجين')], default='onsite', max_length=20, verbose_name='بيئة العمل'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_hours',
            field=models.CharField(blank=True, help_text='مثال: 9-5, 8-4, مرن', max_length=100, verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('closed', 'مغلقة'), ('draft', 'مسودة')], default='active', max_length=20, verbose_name='حالة الوظيفة'),
        ),
    ]
