# Generated by Django 5.2.17 on 2026-08-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0147_remove_job_display_mode_job_education_requirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='advance_booking_days',
            field=models.IntegerField(default=0, verbose_name='أيام الحجز المسبق'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='booking_methods',
            field=models.JSONField(default=list, help_text='طرق الحجز المتاحة', verbose_name='طرق الحجز'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='branch_locations',
            field=models.JSONField(default=list, help_text='مواقع الفروع بالتفصيل', verbose_name='مواقع الفروع'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='branches_count',
            field=models.IntegerField(default=0, verbose_name='عدد الفروع'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='cancellation_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الإلغاء'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='cancellation_policy_en',
            field=models.TextField(blank=True, verbose_name='سياسة الإلغاء بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='certifications',
            field=models.JSONField(default=list, verbose_name='الشهادات والاعتمادات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='daily_capacity',
            field=models.IntegerField(default=0, verbose_name='السعة اليومية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='destinations',
            field=models.JSONField(default=list, help_text='قائمة الوجهات التي تخدمها الشركة', verbose_name='الوجهات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='facilities',
            field=models.JSONField(default=list, help_text='المرافق المتوفرة مثل الحافلات، الفنادق، إلخ', verbose_name='المرافق'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_branches',
            field=models.BooleanField(default=False, verbose_name='لديها فروع'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_special_offers',
            field=models.BooleanField(default=False, verbose_name='عروض خاصة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='انستغرام'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='monthly_capacity',
            field=models.IntegerField(default=0, verbose_name='السعة الشهرية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='partners',
            field=models.JSONField(default=list, verbose_name='الشركاء'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='price_currency',
            field=models.CharField(default='IQD', max_length=10, verbose_name='عملة السعر'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='services',
            field=models.JSONField(default=list, help_text='الخدمات الإضافية مثل التأشيرات، الحجوزات، إلخ', verbose_name='الخدمات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='special_offers',
            field=models.JSONField(default=list, verbose_name='العروض الخاصة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='تيليجرام'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='travel_type',
            field=models.CharField(choices=[('land', 'بري'), ('air', 'جوي'), ('sea', 'بحري'), ('mixed', 'مختلط')], default='land', max_length=20, verbose_name='نوع السفر'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='تويتر'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='working_hours',
            field=models.JSONField(default=dict, help_text='ساعات العمل اليومية', verbose_name='ساعات العمل'),
        ),
        migrations.CreateModel(
            name='TravelCompanyRatingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_service_quality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط جودة الخدمة')),
                ('avg_price_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط القيمة مقابل السعر')),
                ('avg_reliability', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط الموثوقية')),
                ('avg_customer_service', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط خدمة العملاء')),
                ('avg_comfort', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط الراحة')),
                ('rating_1_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 1 نجمة')),
                ('rating_2_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 2 نجمة')),
                ('rating_3_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 3 نجوم')),
                ('rating_4_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 4 نجوم')),
                ('rating_5_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 5 نجوم')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_breakdown', to='properties.travelcompany', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تفاصيل تقييمات شركة سفر',
                'verbose_name_plural': 'تفاصيل تقييمات شركات السفر',
            },
        ),
        migrations.CreateModel(
            name='TravelCompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], verbose_name='التقييم العام')),
                ('service_quality', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='جودة الخدمة')),
                ('price_value', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='القيمة مقابل السعر')),
                ('reliability', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='الموثوقية')),
                ('customer_service', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='خدمة العملاء')),
                ('comfort', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='الراحة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('comment_en', models.TextField(blank=True, verbose_name='التعليق بالإنجليزية')),
                ('trip_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرحلة')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='الوجهة')),
                ('travel_type', models.CharField(blank=True, max_length=50, verbose_name='نوع السفر')),
                ('images', models.JSONField(default=list, verbose_name='صور التقييم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.travelcompany', verbose_name='الشركة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_company_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم شركة سفر',
                'verbose_name_plural': 'تقييمات شركات السفر',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'user')},
            },
        ),
    ]
