# Generated by Django 5.2.17 on 2026-08-12 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0148_travelcompany_advance_booking_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم هاتف العميل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد إلكتروني العميل')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('booking_time', models.TimeField(verbose_name='وقت الحجز')),
                ('duration', models.IntegerField(default=60, verbose_name='المدة (دقيقة)')),
                ('location_type', models.CharField(choices=[('provider_location', 'موقع مقدم الخدمة'), ('customer_location', 'موقع العميل'), ('online', 'عن بعد')], default='provider_location', max_length=20, verbose_name='نوع الموقع')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الدفعة المقدمة')),
                ('currency', models.CharField(default='IQD', max_length=10, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'مدفوع جزئياً'), ('paid', 'مدفوع'), ('refunded', 'مسترد')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات العميل')),
                ('provider_notes', models.TextField(blank=True, verbose_name='ملاحظات مقدم الخدمة')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='تم إرسال التذكير')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='تم إرسال التأكيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('provider_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.serviceproviderpage', verbose_name='صفحة مقدم الخدمة')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.serviceproviderservice', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'حجز خدمة',
                'verbose_name_plural': 'حجوزات الخدمات',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('availability_type', models.CharField(choices=[('available', 'متاح'), ('unavailable', 'غير متاح'), ('busy', 'مشغول')], default='available', max_length=20, verbose_name='نوع التوافر')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='properties.serviceproviderpage', verbose_name='مقدم الخدمة')),
            ],
            options={
                'verbose_name': 'توافر مقدم الخدمة',
                'verbose_name_plural': 'توافر مقدمي الخدمات',
                'ordering': ['date', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderRatingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_quality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط جودة العمل')),
                ('avg_professionalism', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط الاحترافية')),
                ('avg_punctuality', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط المواعيد')),
                ('avg_communication', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط التواصل')),
                ('avg_value_for_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط القيمة مقابل السعر')),
                ('rating_1_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 1 نجمة')),
                ('rating_2_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 2 نجمة')),
                ('rating_3_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 3 نجوم')),
                ('rating_4_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 4 نجوم')),
                ('rating_5_count', models.IntegerField(default=0, verbose_name='عدد التقييمات 5 نجوم')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_breakdown', to='properties.serviceproviderpage', verbose_name='مقدم الخدمة')),
            ],
            options={
                'verbose_name': 'تفاصيل تقييمات مقدم خدمة',
                'verbose_name_plural': 'تفاصيل تقييمات مقدمي الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('overall_rating', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], verbose_name='التقييم العام')),
                ('quality', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='جودة العمل')),
                ('professionalism', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='الاحترافية')),
                ('punctuality', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='المواعيد')),
                ('communication', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='التواصل')),
                ('value_for_money', models.IntegerField(choices=[(1, 'سيء جداً'), (2, 'سيء'), (3, 'متوسط'), (4, 'جيد'), (5, 'ممتاز')], default=3, verbose_name='القيمة مقابل السعر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الخدمة')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الخدمة')),
                ('images', models.JSONField(default=list, verbose_name='صور التقييم')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('is_approved', models.BooleanField(default=True, verbose_name='موافق عليه')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='properties.servicebooking', verbose_name='الحجز')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_reviews', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.serviceproviderpage', verbose_name='مقدم الخدمة')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='properties.serviceproviderservice', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'تقييم مقدم خدمة',
                'verbose_name_plural': 'تقييمات مقدمي الخدمات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=20, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='وقت بداية الاستراحة')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='وقت نهاية الاستراحة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('max_bookings', models.IntegerField(default=1, verbose_name='أقصى عدد حجوزات')),
                ('booking_duration', models.IntegerField(default=60, verbose_name='مدة الحجز (دقيقة)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='properties.serviceproviderpage', verbose_name='مقدم الخدمة')),
            ],
            options={
                'verbose_name': 'جدول مواعيد',
                'verbose_name_plural': 'جداول المواعيد',
                'ordering': ['provider', 'day', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['booking_date', 'booking_time'], name='properties__booking_b6bda0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['status'], name='properties__status_5fce4b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['customer'], name='properties__custome_a580d2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['provider_page'], name='properties__provide_d6f6f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovideravailability',
            unique_together={('provider', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceproviderreview',
            unique_together={('provider', 'customer', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceproviderschedule',
            unique_together={('provider', 'day')},
        ),
    ]
