# Generated by Django 5.2.17 on 2026-08-12 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0149_servicebooking_serviceprovideravailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف إضافي'),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الوكيل'),
        ),
        migrations.AddField(
            model_name='property',
            name='annual_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='العائد السنوي المتوقع'),
        ),
        migrations.AddField(
            model_name='property',
            name='attic_storage',
            field=models.BooleanField(default=False, verbose_name='مخزن في العلية'),
        ),
        migrations.AddField(
            model_name='property',
            name='available_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات التوفر'),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة الشرفة (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='basement_storage',
            field=models.BooleanField(default=False, verbose_name='مخزن في القبو'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('master', 'رئيسي'), ('guest', 'ضيوف'), ('shared', 'مشترك'), ('ensuite', 'ملحق')], max_length=30, null=True, verbose_name='نوع الحمام'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_permit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ رخصة البناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_permit_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرخصة'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_permit_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم رخصة البناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=200, verbose_name='دعوة للعمل'),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_service',
            field=models.BooleanField(default=False, verbose_name='خدمة تنظيف'),
        ),
        migrations.AddField(
            model_name='property',
            name='click_through_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل النقر (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة العمولة (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='completeness_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درجة الاكتمال (1-100)'),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_quality',
            field=models.CharField(blank=True, choices=[('luxury', 'فاخر'), ('high', 'عالي الجودة'), ('medium', 'متوسط'), ('basic', 'أساسي'), ('economy', 'اقتصادي')], max_length=30, null=True, verbose_name='جودة البناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل التحويل (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='covered_parking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مواقف مغطاة'),
        ),
        migrations.AddField(
            model_name='property',
            name='current_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الإيجار الحالي'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تصنيف مخصص'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الطابو'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الطابو'),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_type',
            field=models.CharField(blank=True, choices=[('title_deed', 'طابو'), ('agricultural', 'زراعي'), ('investment', 'استثماري'), ('commercial', 'تجاري'), ('residential', 'سكني'), ('shared', 'مشاع'), ('municipal', 'بلدي')], max_length=30, null=True, verbose_name='نوع الوثيقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='display_windows',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد واجهات العرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_hospitals',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='المسافة للمستشفيات (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_main_road',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='المسافة للطريق الرئيسي (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_markets',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='المسافة للأسواق (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_schools',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='المسافة للمدارس (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='down_payment_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة الدفعة الأولى (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='driver_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد غرف السائق'),
        ),
        migrations.AddField(
            model_name='property',
            name='eco_friendly',
            field=models.BooleanField(default=False, verbose_name='صديق للبيئة'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_phase',
            field=models.CharField(blank=True, choices=[('single', 'أحادي الطور'), ('three', 'ثلاثي الطور'), ('none', 'لا يوجد')], max_length=20, null=True, verbose_name='نوع الكهرباء'),
        ),
        migrations.AddField(
            model_name='property',
            name='external_storage',
            field=models.BooleanField(default=False, verbose_name='مخزن خارجي'),
        ),
        migrations.AddField(
            model_name='property',
            name='garden_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة الحديقة (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_3d_tour',
            field=models.BooleanField(default=False, verbose_name='جولة ثلاثية الأبعاد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_accessible_bathroom',
            field=models.BooleanField(default=False, verbose_name='حمام متاح'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_bbq_area',
            field=models.BooleanField(default=False, verbose_name='منطقة شواء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_biometric_lock',
            field=models.BooleanField(default=False, verbose_name='قفل بيومتري'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dining_area',
            field=models.BooleanField(default=False, verbose_name='منطقة طعام'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_driver_room',
            field=models.BooleanField(default=False, verbose_name='غرفة سائق'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ensuite_bathroom',
            field=models.BooleanField(default=False, verbose_name='حمام ملحق'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_family_room',
            field=models.BooleanField(default=False, verbose_name='غرفة عائلة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_fireplace',
            field=models.BooleanField(default=False, verbose_name='مدفأة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='كراج'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_greenhouse',
            field=models.BooleanField(default=False, verbose_name='بيت زجاج'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_guest_bathroom',
            field=models.BooleanField(default=False, verbose_name='حمام ضيوف'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_home_office',
            field=models.BooleanField(default=False, verbose_name='مكتب منزلي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_intercom',
            field=models.BooleanField(default=False, verbose_name='نظام اتصال داخلي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_irrigation',
            field=models.BooleanField(default=False, verbose_name='نظام ري'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_jacuzzi',
            field=models.BooleanField(default=False, verbose_name='جاكوزي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_legal_disputes',
            field=models.BooleanField(default=False, verbose_name='نزاعات قانونية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='مكتبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_living_room',
            field=models.BooleanField(default=False, verbose_name='صالة معيشة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_loading_dock',
            field=models.BooleanField(default=False, verbose_name='رصيف تحميل'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_maid_room',
            field=models.BooleanField(default=False, verbose_name='غرفة خادمة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_master_bathroom',
            field=models.BooleanField(default=False, verbose_name='حمام رئيسي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_master_bedroom',
            field=models.BooleanField(default=False, verbose_name='غرفة رئيسية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_office_space',
            field=models.BooleanField(default=False, verbose_name='مساحة مكتبية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_playground',
            field=models.BooleanField(default=False, verbose_name='ملعب'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_rainwater_harvesting',
            field=models.BooleanField(default=False, verbose_name='جمع مياه الأمطار'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_renovations',
            field=models.BooleanField(default=False, verbose_name='تم تجديده'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sauna',
            field=models.BooleanField(default=False, verbose_name='ساونا'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_showroom',
            field=models.BooleanField(default=False, verbose_name='صالة عرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smart_lock',
            field=models.BooleanField(default=False, verbose_name='قفل ذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar_panels',
            field=models.BooleanField(default=False, verbose_name='ألواح شمسية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sports_court',
            field=models.BooleanField(default=False, verbose_name='ملعب رياضي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_storage',
            field=models.BooleanField(default=False, verbose_name='مخزن'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_study_room',
            field=models.BooleanField(default=False, verbose_name='غرفة دراسة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_video_doorbell',
            field=models.BooleanField(default=False, verbose_name='جرس فيديو'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_walk_in_closet',
            field=models.BooleanField(default=False, verbose_name='خزانة مشي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_warehouse',
            field=models.BooleanField(default=False, verbose_name='مستودع'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_warehouse_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ارتفاع المستودع (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_warehouse_space',
            field=models.BooleanField(default=False, verbose_name='مساحة مستودع'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_waste_management',
            field=models.BooleanField(default=False, verbose_name='نظام إدارة النفايات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_well',
            field=models.BooleanField(default=False, verbose_name='بئر'),
        ),
        migrations.AddField(
            model_name='property',
            name='highlights',
            field=models.TextField(blank=True, verbose_name='نقاط التمييز'),
        ),
        migrations.AddField(
            model_name='property',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة الفائدة (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('rental', 'إيجاري'), ('commercial', 'تجاري'), ('residential', 'سكني'), ('mixed', 'مختلط'), ('agricultural', 'زراعي'), ('industrial', 'صناعي')], max_length=30, null=True, verbose_name='نوع الاستثمار'),
        ),
        migrations.AddField(
            model_name='property',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('drip', 'تنقيط'), ('sprinkler', 'رشاش'), ('flood', 'غمر'), ('manual', 'يدوي'), ('none', 'لا يوجد')], max_length=30, null=True, verbose_name='نوع الري'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_smart_home',
            field=models.BooleanField(default=False, verbose_name='منزل ذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='عاجل'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='متحقق منه'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_appliances',
            field=models.TextField(blank=True, verbose_name='أجهزة المطبخ'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_type',
            field=models.CharField(blank=True, choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('semi_open', 'نصف مفتوحة'), ('american', 'أمريكية')], max_length=30, null=True, verbose_name='نوع المطبخ'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الأرض'),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('clear', 'خالي من النزاعات'), ('disputed', 'متنازع عليه'), ('court_case', 'قضية محكمة'), ('inherited', 'موروث'), ('shared', 'مشاع')], max_length=30, null=True, verbose_name='الحالة القانونية'),
        ),
        migrations.AddField(
            model_name='property',
            name='loan_term',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدة القرض (سنوات)'),
        ),
        migrations.AddField(
            model_name='property',
            name='maid_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد غرف الخدم'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_service',
            field=models.BooleanField(default=False, verbose_name='خدمة صيانة'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_status',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('needs_work', 'يحتاج عمل'), ('poor', 'سيء')], max_length=30, null=True, verbose_name='حالة الصيانة'),
        ),
        migrations.AddField(
            model_name='property',
            name='market_demand',
            field=models.CharField(blank=True, choices=[('high', 'طلب عالي'), ('medium', 'طلب متوسط'), ('low', 'طلب منخفض'), ('unknown', 'غير معروف')], max_length=30, null=True, verbose_name='الطلب في السوق'),
        ),
        migrations.AddField(
            model_name='property',
            name='marketing_description',
            field=models.TextField(blank=True, verbose_name='وصف تسويقي'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الدفع الشهري'),
        ),
        migrations.AddField(
            model_name='property',
            name='mortgage_available',
            field=models.BooleanField(default=False, verbose_name='متاح للرهن'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_facilities',
            field=models.TextField(blank=True, verbose_name='مرافق قريبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_quality',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('average', 'متوسط'), ('developing', 'قيد التطوير'), ('rural', 'ريفي')], max_length=30, null=True, verbose_name='جودة الحي'),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسبة الإشغال (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='open_parking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مواقف مكشوفة'),
        ),
        migrations.AddField(
            model_name='property',
            name='orchard_trees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد أشجار البستان'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_address',
            field=models.TextField(blank=True, verbose_name='عنوان المالك'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد المالك'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف المالك'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_relationship',
            field=models.CharField(blank=True, choices=[('owner', 'المالك'), ('agent', 'وكيل'), ('family', 'عائلة'), ('friend', 'صديق'), ('company', 'شركة')], max_length=30, null=True, verbose_name='علاقة المالك'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المخطط'),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'هاتف'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('in_person', 'شخصيا'), ('any', 'أي وسيلة')], max_length=30, null=True, verbose_name='طريقة التواصل المفضلة'),
        ),
        migrations.AddField(
            model_name='property',
            name='previous_owners',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد المالكين السابقين'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_trend',
            field=models.CharField(blank=True, choices=[('rising', 'تصاعدي'), ('stable', 'مستقر'), ('declining', 'تنازلي'), ('unknown', 'غير معروف')], max_length=30, null=True, verbose_name='اتجاه السعر'),
        ),
        migrations.AddField(
            model_name='property',
            name='priority_score',
            field=models.IntegerField(default=0, verbose_name='درجة الأولوية'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_management',
            field=models.BooleanField(default=False, verbose_name='إدارة عقارات'),
        ),
        migrations.AddField(
            model_name='property',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درجة الجودة (1-100)'),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation_details',
            field=models.TextField(blank=True, verbose_name='تفاصيل التجديد'),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة التجديد'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_history',
            field=models.TextField(blank=True, verbose_name='تاريخ الإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='العائد الإيجاري (%)'),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='محجوز'),
        ),
        migrations.AddField(
            model_name='property',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='محجوز حتى'),
        ),
        migrations.AddField(
            model_name='property',
            name='road_type',
            field=models.CharField(blank=True, choices=[('paved', 'معبّد'), ('unpaved', 'غير معبّد'), ('asphalt', 'إسفلت'), ('concrete', 'خرسانة'), ('dirt', 'ترابي')], max_length=30, null=True, verbose_name='نوع الطريق'),
        ),
        migrations.AddField(
            model_name='property',
            name='section_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم القسيمة'),
        ),
        migrations.AddField(
            model_name='property',
            name='security_service',
            field=models.BooleanField(default=False, verbose_name='خدمة أمان'),
        ),
        migrations.AddField(
            model_name='property',
            name='smart_features',
            field=models.TextField(blank=True, verbose_name='مميزات المنزل الذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='social_media_links',
            field=models.TextField(blank=True, verbose_name='روابط التواصل الاجتماعي'),
        ),
        migrations.AddField(
            model_name='property',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البيع'),
        ),
        migrations.AddField(
            model_name='property',
            name='special_features',
            field=models.TextField(blank=True, verbose_name='مميزات خاصة'),
        ),
        migrations.AddField(
            model_name='property',
            name='storage_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد المخازن'),
        ),
        migrations.AddField(
            model_name='property',
            name='street_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض الشارع (متر)'),
        ),
        migrations.AddField(
            model_name='property',
            name='supports_video_call',
            field=models.BooleanField(default=False, verbose_name='يدعم مكالمة فيديو'),
        ),
        migrations.AddField(
            model_name='property',
            name='tags',
            field=models.TextField(blank=True, verbose_name='الكلمات المفتاحية'),
        ),
        migrations.AddField(
            model_name='property',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب تيليجرام'),
        ),
        migrations.AddField(
            model_name='property',
            name='terrace_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة التراس (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='time_on_market',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الوقت في السوق (أيام)'),
        ),
        migrations.AddField(
            model_name='property',
            name='under_contract',
            field=models.BooleanField(default=False, verbose_name='تحت العقد'),
        ),
        migrations.AddField(
            model_name='property',
            name='unique_selling_points',
            field=models.TextField(blank=True, verbose_name='نقاط البيع الفريدة'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgent_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='عاجل حتى'),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق'),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_properties', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_call_available',
            field=models.BooleanField(default=False, verbose_name='مكالمة فيديو متاحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='viewing_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات المعاينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_available',
            field=models.BooleanField(default=False, verbose_name='جولة افتراضية متاحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_link',
            field=models.URLField(blank=True, verbose_name='رابط الجولة الافتراضية'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, choices=[('municipal', 'بلدي'), ('well', 'بئر'), ('tanker', 'صهريج'), ('bottled', 'عبوات'), ('none', 'لا يوجد')], max_length=30, null=True, verbose_name='مصدر الماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
        migrations.AddField(
            model_name='property',
            name='yard_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة الفناء (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='years_since_construction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد السنوات منذ البناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning_type',
            field=models.CharField(blank=True, choices=[('residential', 'سكني'), ('commercial', 'تجاري'), ('mixed', 'مختلط'), ('industrial', 'صناعي'), ('agricultural', 'زراعي'), ('tourist', 'سياحي'), ('educational', 'تعليمي'), ('health', 'صحي')], max_length=30, null=True, verbose_name='نوع المنطقة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ar_available',
            field=models.BooleanField(default=False, verbose_name='واقع معزز متاح'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='رامب دخول'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('garage', 'كراج'), ('carport', 'مظلة سيارات'), ('open', 'مفتوح'), ('street', 'شارع'), ('underground', 'تحت الأرض')], max_length=30, null=True, verbose_name='نوع الموقف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='view_type',
            field=models.CharField(blank=True, choices=[('city', 'إطلالة مدينة'), ('sea', 'إطلالة بحر'), ('mountain', 'إطلالة جبل'), ('garden', 'إطلالة حديقة'), ('street', 'إطلالة شارع'), ('park', 'إطلالة حديقة عامة'), ('river', 'إطلالة نهر'), ('lake', 'إطلالة بحيرة'), ('mosque', 'إطلالة مسجد'), ('school', 'إطلالة مدرسة'), ('market', 'إطلالة سوق'), ('none', 'لا يوجد')], max_length=50, verbose_name='نوع الإطلالة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False, verbose_name='متاح للكراسي المتحركة'),
        ),
    ]
