# Generated by Django 5.2.17 on 2026-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0150_property_additional_phone_property_agent_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideproperty',
            name='accessible_bathroom',
            field=models.BooleanField(default=False, verbose_name='حمام متاح'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='annual_maintenance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الصيانة السنوية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الشقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='appreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل النمو (%)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='average_temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متوسط درجة الحرارة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='bbq_area',
            field=models.BooleanField(default=False, verbose_name='منطقة شواء'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='building_certification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهادة البناء'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم المبنى'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='building_type',
            field=models.CharField(blank=True, choices=[('apartment', 'شقة'), ('house', 'منزل'), ('villa', 'فيلا'), ('townhouse', 'منزل صفين'), ('condo', 'شقة ملكية'), ('penthouse', 'شقة دوبلكس'), ('studio', 'ستوديو'), ('loft', 'لوفت'), ('mansion', 'قصر'), ('cottage', 'كوخ'), ('commercial', 'تجاري'), ('industrial', 'صناعي'), ('land', 'أرض')], max_length=50, null=True, verbose_name='نوع المبنى'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='buyer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المشتري'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='carbon_monoxide_detectors',
            field=models.BooleanField(default=False, verbose_name='مكتشفات أول أكسيد الكربون'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='cinema_room',
            field=models.BooleanField(default=False, verbose_name='غرفة سينما'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='city_view',
            field=models.BooleanField(default=False, verbose_name='إطلالة مدينة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='climate_type',
            field=models.CharField(blank=True, choices=[('tropical', 'استوائي'), ('temperate', 'معتدل'), ('arid', 'جاف'), ('continental', 'قاري'), ('mediterranean', 'متوسطي'), ('polar', 'قطبي')], max_length=50, null=True, verbose_name='نوع المناخ'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='community_center',
            field=models.BooleanField(default=False, verbose_name='مركز مجتمعي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='construction_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة البناء'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='county_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المقاطعة أو المنطقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='deed_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السند'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='distance_to_airport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسافة للمطار (كم)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='distance_to_beach',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسافة للشاطئ (كم)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='distance_to_city_center',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسابة لمركز المدينة (كم)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='distance_to_ski_resort',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='المسافة لمنتجع التزلج (كم)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='energy_efficient',
            field=models.BooleanField(default=False, verbose_name='كفاءة الطاقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='energy_rating',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تصنيف الطاقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='ensuite_bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حمامات ملحقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='external_storage',
            field=models.BooleanField(default=False, verbose_name='تخزين خارجي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='fire_pit',
            field=models.BooleanField(default=False, verbose_name='موقد ناري'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='fire_safety',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سلامة الحريق'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مفروش'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='gated_community',
            field=models.BooleanField(default=False, verbose_name='مجمع مسور'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='golf_course',
            field=models.BooleanField(default=False, verbose_name='ملعب غولف'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='green_building_certified',
            field=models.BooleanField(default=False, verbose_name='مبنى أخضر معتمد'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='guest_bathrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حمامات ضيوف'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='gym_room',
            field=models.BooleanField(default=False, verbose_name='غرفة رياضية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_attic',
            field=models.BooleanField(default=False, verbose_name='علية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='شرفة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_basement',
            field=models.BooleanField(default=False, verbose_name='قبو'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='مصعد'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='كراج'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='حديقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='موقف سيارات'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_ramp',
            field=models.BooleanField(default=False, verbose_name='رامب دخول'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='تراس'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='home_office',
            field=models.BooleanField(default=False, verbose_name='مكتب منزلي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='humidity_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مستوى الرطوبة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='insulation_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العزل'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شركة التأمين'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التأمين'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم بوليصة التأمين'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قسط التأمين'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='international_hospitals_nearby',
            field=models.BooleanField(default=False, verbose_name='مستشفيات دولية قريبة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='international_schools_nearby',
            field=models.BooleanField(default=False, verbose_name='مدارس دولية قريبة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='is_under_contract',
            field=models.BooleanField(default=False, verbose_name='تحت العقد'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='kitchen_appliances',
            field=models.TextField(blank=True, verbose_name='أجهزة المطبخ'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='kitchen_type',
            field=models.CharField(blank=True, choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('semi_open', 'نصف مفتوحة'), ('american', 'أمريكية')], max_length=30, null=True, verbose_name='نوع المطبخ'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='lake_view',
            field=models.BooleanField(default=False, verbose_name='إطلالة بحيرة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='land_registry_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم سجل الأراضي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='last_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر فحص'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='legal_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رسوم قانونية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='listing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإدراج'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='management_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='رسوم الإدارة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='monthly_utilities_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تقدير المرافق الشهرية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='mountain_view',
            field=models.BooleanField(default=False, verbose_name='إطلالة جبال'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص القادم'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='ocean_view',
            field=models.BooleanField(default=False, verbose_name='إطلالة محيط'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='outdoor_kitchen',
            field=models.BooleanField(default=False, verbose_name='مطبخ خارجي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='outdoor_shower',
            field=models.BooleanField(default=False, verbose_name='دش خارجي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='ownership_restrictions',
            field=models.TextField(blank=True, verbose_name='قيود التملك'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='park_view',
            field=models.BooleanField(default=False, verbose_name='إطلالة حديقة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد مواقف السيارات'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='partially_furnished',
            field=models.BooleanField(default=False, verbose_name='مفروش جزئيا'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='pet_restrictions',
            field=models.TextField(blank=True, verbose_name='قيود الحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='playground',
            field=models.BooleanField(default=False, verbose_name='ملعب'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='مروّج'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('needs_renovation', 'يحتاج تجديد'), ('poor', 'سيء')], max_length=30, null=True, verbose_name='حالة العقار'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='property_management_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شركة إدارة العقارات'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='public_transport_access',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وصول النقل العام'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='rainwater_harvesting',
            field=models.BooleanField(default=False, verbose_name='جمع مياه الأمطار'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التسجيل'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='renovation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سنة التجديد'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='rental_yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='العائد الإيجاري (%)'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='residency_requirements',
            field=models.TextField(blank=True, verbose_name='متطلبات الإقامة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='security_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام الأمان'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='seller_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات البائع'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='smart_home_enabled',
            field=models.BooleanField(default=False, verbose_name='منزل ذكي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='smart_lighting',
            field=models.BooleanField(default=False, verbose_name='إضاءة ذكية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='smart_security',
            field=models.BooleanField(default=False, verbose_name='أمان ذكي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='smart_thermostat',
            field=models.BooleanField(default=False, verbose_name='منظم حرارة ذكي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='smoke_detectors',
            field=models.BooleanField(default=False, verbose_name='مكتشفات الدخان'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='solar_panels',
            field=models.BooleanField(default=False, verbose_name='ألواح شمسية'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='sold_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البيع'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رسوم الطابع'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='storage_room',
            field=models.BooleanField(default=False, verbose_name='غرفة تخزين'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الشارع'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='tennis_court',
            field=models.BooleanField(default=False, verbose_name='ملعب تنس'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='tourist_demand',
            field=models.CharField(blank=True, choices=[('high', 'عالي'), ('medium', 'متوسط'), ('low', 'منخفض'), ('seasonal', 'موسمي')], max_length=30, null=True, verbose_name='الطلب السياحي'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='transfer_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ضريبة التحويل'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='unfurnished',
            field=models.BooleanField(default=False, verbose_name='غير مفروش'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='utility_provider_electric',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مزود الكهرباء'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='utility_provider_gas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مزود الغاز'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='utility_provider_internet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مزود الإنترنت'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='utility_provider_water',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مزود الماء'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='video_tour_available',
            field=models.BooleanField(default=False, verbose_name='جولة فيديو متاحة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='viewing_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات المعاينة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='virtual_tour_available',
            field=models.BooleanField(default=False, verbose_name='جولة افتراضية متاحة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='visa_requirements',
            field=models.TextField(blank=True, verbose_name='متطلبات التأشيرة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False, verbose_name='متاح للكراسي المتحركة'),
        ),
        migrations.AddField(
            model_name='outsideproperty',
            name='wine_cellar',
            field=models.BooleanField(default=False, verbose_name='قبو نبيذ'),
        ),
    ]
