# Generated by Django 5.2.17 on 2026-08-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0151_outsideproperty_accessible_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrequest',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_requests', to='properties.property', verbose_name='الإعلان المرتبط'),
        ),
    ]
