# Generated by Django 5.2.17 on 2026-08-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0152_buildingrequest_related_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrequest',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='buildingrequest',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء'),
        ),
    ]
