# Generated by Django 5.2.17 on 2026-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0153_buildingrequest_area_buildingrequest_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='auction',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='auction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='auction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='auction',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='building_requests/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='buildingrequest',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'بيت'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('duplex', 'دوبلكس'), ('residential_complex', 'مجمع سكني'), ('penthouse', 'بنتهاوس'), ('studio', 'ستوديو'), ('townhouse', 'تاون هاوس'), ('shop', 'محل'), ('office', 'مكتب'), ('mall', 'مول / مركز تجاري'), ('car_showroom', 'معرض سيارات'), ('warehouse', 'مخزن'), ('tower', 'برج'), ('factory', 'معمل'), ('clinic', 'عيادة'), ('pharmacy', 'صيدلية'), ('restaurant', 'مطعم'), ('cafe', 'مقهى'), ('residential_building', 'بناية سكنية'), ('commercial_building', 'عمارة تجارية'), ('investment_land', 'أرض للاستثمار'), ('apartment_complex', 'مجمع شقق'), ('small_hotel', 'فندق صغير'), ('investment_property', 'عقار استثماري'), ('chalet', 'شاليه'), ('resort', 'منتجع'), ('hotel', 'فندق'), ('hotel_apartment', 'شقق فندقية'), ('tourism_house', 'بيت سياحي'), ('tourist_farm', 'مزرعة سياحية'), ('beach_house', 'بيت شاطئي'), ('rest_house', 'استراحة'), ('camp_site', 'مخيم'), ('tourist_city', 'مدينة سياحية'), ('cabin', 'كوخ'), ('residential_land', 'أرض سكنية'), ('agricultural_land', 'أرض زراعية'), ('commercial_land', 'أرض تجارية'), ('investment_land', 'أرض استثمارية'), ('residential_building', 'بناية سكنية'), ('commercial_building', 'بناية تجارية'), ('industrial_building', 'بناية صناعية'), ('mixed_use_building', 'بناية مختلطة الاستخدام'), ('under_construction', 'قيد البناء'), ('building_project', 'مشروع بناء'), ('outside_apartment', 'شقة خارج العراق'), ('outside_villa', 'فيلا خارج العراق'), ('outside_palace', 'قصر خارج العراق'), ('outside_house', 'منزل خارج العراق'), ('outside_land', 'أرض خارج العراق'), ('outside_commercial', 'عقار تجاري خارج العراق')], max_length=50, verbose_name='نوع العقار'),
        ),
    ]
