# Generated by Django 5.2.17 on 2026-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0154_auction_additional_images_auction_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
    ]
