# Generated by Django 5.2.17 on 2026-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0155_travelcompany_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='job',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='resort',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
    ]
