# Generated by Django 5.2.17 on 2026-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0156_hotel_additional_images_hotel_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcompany',
            name='accepts_installments',
            field=models.BooleanField(default=False, verbose_name='يقبل التقسيط'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='awards',
            field=models.JSONField(blank=True, default=list, verbose_name='الجوائز والتقديرات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='covid_measures',
            field=models.TextField(blank=True, verbose_name='إجراءات كوفيد-19'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='custom_packages',
            field=models.BooleanField(default=False, verbose_name='باقات مخصصة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='جهات اتصال الطوارئ'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف الطوارئ'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='emergency_protocols',
            field=models.TextField(blank=True, verbose_name='بروتوكولات الطوارئ'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='featured_testimonials',
            field=models.JSONField(blank=True, default=list, verbose_name='شهادات العملاء المميزة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='fleet_information',
            field=models.JSONField(blank=True, default=dict, verbose_name='معلومات الأسطول'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='fleet_maintenance',
            field=models.TextField(blank=True, verbose_name='صيانة الأسطول'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_24_7_support',
            field=models.BooleanField(default=False, verbose_name='دعم 24/7'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_hotel_partnerships',
            field=models.BooleanField(default=False, verbose_name='لديه شراكات فندقية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_loyalty_program',
            field=models.BooleanField(default=False, verbose_name='برنامج ولاء'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_multilingual_staff',
            field=models.BooleanField(default=False, verbose_name='موظفون متعددو اللغات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_safety_certification',
            field=models.BooleanField(default=False, verbose_name='شهادة سلامة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='has_seasonal_offers',
            field=models.BooleanField(default=False, verbose_name='عروض موسمية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='health_guidelines',
            field=models.TextField(blank=True, verbose_name='إرشادات صحية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='hotel_discounts',
            field=models.TextField(blank=True, verbose_name='خصومات الفنادق'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='hotel_partners',
            field=models.JSONField(blank=True, default=list, verbose_name='الفنادق الشريكة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='installment_options',
            field=models.JSONField(blank=True, default=list, verbose_name='خيارات التقسيط'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='insurance_coverage',
            field=models.TextField(blank=True, verbose_name='تغطية التأمين'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='insurance_providers',
            field=models.JSONField(blank=True, default=list, verbose_name='شركات التأمين'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='international_coverage',
            field=models.JSONField(blank=True, default=list, verbose_name='التغطية الدولية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=200, verbose_name='جهة الإصدار'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='languages_spoken',
            field=models.JSONField(default=list, verbose_name='اللغات المتحدثة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الترخيص'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الترخيص'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='loyalty_benefits',
            field=models.TextField(blank=True, verbose_name='مزايا الولاء'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='offers_packages',
            field=models.BooleanField(default=False, verbose_name='يقدم باقات سياحية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='payment_methods',
            field=models.JSONField(default=list, help_text='طرق الدفع المتاحة', verbose_name='طرق الدفع'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='points_system',
            field=models.JSONField(blank=True, default=dict, verbose_name='نظام النقاط'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='provides_travel_insurance',
            field=models.BooleanField(default=False, verbose_name='يقدم تأمين سفر'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='provides_visa_services',
            field=models.BooleanField(default=False, verbose_name='يقدم خدمات التأشيرة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='recognitions',
            field=models.JSONField(blank=True, default=list, verbose_name='الاعترافات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='refund_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الاسترداد'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='refund_policy_en',
            field=models.TextField(blank=True, verbose_name='سياسة الاسترداد بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='refund_processing_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='أيام معالجة الاسترداد'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='safety_measures',
            field=models.TextField(blank=True, verbose_name='إجراءات السلامة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='seasonal_offers',
            field=models.JSONField(blank=True, default=list, verbose_name='العروض الموسمية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='service_areas',
            field=models.JSONField(default=list, verbose_name='مناطق الخدمة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='support_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات الدعم'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف الدعم'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='terms_conditions',
            field=models.TextField(blank=True, verbose_name='الشروط والأحكام'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='terms_conditions_en',
            field=models.TextField(blank=True, verbose_name='الشروط والأحكام بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='tour_packages',
            field=models.JSONField(blank=True, default=list, verbose_name='الباقات السياحية'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='vehicle_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع المركبات'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='visa_countries',
            field=models.JSONField(blank=True, default=list, verbose_name='دول التأشيرة'),
        ),
        migrations.AddField(
            model_name='travelcompany',
            name='visa_processing_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='وقت معالجة التأشيرة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='company_type',
            field=models.CharField(choices=[('tourism', 'سياحة'), ('hajj_umrah', 'حج وعمرة'), ('business', 'أعمال'), ('adventure', 'مغامرة'), ('medical', 'سياحة علاجية'), ('educational', 'سياحة تعليمية'), ('family', 'عائلات'), ('luxury', 'فاخرة'), ('budget', 'اقتصادية'), ('cultural', 'ثقافية'), ('religious', 'دينية'), ('ecotourism', 'سياحة بيئية'), ('cruise', 'رحلات بحرية'), ('wedding_honeymoon', 'زفاف وشهر عسل'), ('student', 'طلاب'), ('senior', 'كبار السن'), ('accessible', 'ذوي احتياجات خاصة'), ('corporate', 'شركات'), ('group_tours', 'رحلات جماعية'), ('private_tours', 'رحلات خاصة'), ('custom_packages', 'باقات مخصصة')], max_length=50, verbose_name='نوع الشركة'),
        ),
    ]
