# Generated by Django 5.2.17 on 2026-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0157_travelcompany_accepts_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resortinsideiraq',
            name='accepts_installments',
            field=models.BooleanField(default=False, verbose_name='يقبل التقسيط'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='accessibility_features',
            field=models.JSONField(blank=True, default=list, verbose_name='ميزات إمكانية الوصول'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='activity_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='جدول الأنشطة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='advance_booking_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='أيام الحجز المسبق'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='awards',
            field=models.JSONField(blank=True, default=list, verbose_name='الجوائز'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='bar_available',
            field=models.BooleanField(default=False, verbose_name='بار متاح'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='booking_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الحجز'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='business_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الأعمال'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='cancellation_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الإلغاء'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='الشهادات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='distance_to_attractions',
            field=models.JSONField(blank=True, default=dict, verbose_name='المسافة للمعالم'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='dress_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزي المطلوب'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='جهات اتصال الطوارئ'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='entertainment_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الترفيه'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='event_venues',
            field=models.JSONField(blank=True, default=list, verbose_name='قاعات المناسبات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='has_24_7_reception',
            field=models.BooleanField(default=False, verbose_name='استقبال 24/7'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='has_medical_services',
            field=models.BooleanField(default=False, verbose_name='خدمات طبية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='has_safety_certification',
            field=models.BooleanField(default=False, verbose_name='شهادة سلامة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='حراسة أمنية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='holiday_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='رسامة العطل'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='meal_options',
            field=models.JSONField(blank=True, default=list, verbose_name='خيارات الوجبات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='minimum_stay_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='أقل مدة إقامة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='nearby_attractions',
            field=models.JSONField(blank=True, default=list, verbose_name='المعالم القريبة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='organized_activities',
            field=models.JSONField(blank=True, default=list, verbose_name='الأنشطة المنظمة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الدفع'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='provides_transportation',
            field=models.BooleanField(default=False, verbose_name='يقدم مواصلات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='restaurant_cuisine',
            field=models.JSONField(blank=True, default=list, verbose_name='مطاعم'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='room_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع الغرف'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='safety_measures',
            field=models.TextField(blank=True, verbose_name='إجراءات السلامة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='seasonal_pricing',
            field=models.JSONField(blank=True, default=dict, verbose_name='التسعير الموسمية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='services_additional',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات الإضافية'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='services_cost',
            field=models.JSONField(blank=True, default=dict, verbose_name='تكلفة الخدمات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='services_included',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات المشمولة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='smoking_policy',
            field=models.CharField(blank=True, max_length=50, verbose_name='سياسة التدخين'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='sports_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الرياضة'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='suite_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع السويت'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف الدعم'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة المواصلات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='transportation_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع المواصلات'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='resortinsideiraq',
            name='weekend_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='رسامة عطلة نهاية الأسبوع'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='accepts_installments',
            field=models.BooleanField(default=False, verbose_name='يقبل التقسيط'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='accessibility_features',
            field=models.JSONField(blank=True, default=list, verbose_name='ميزات إمكانية الوصول'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='activity_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='جدول الأنشطة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='advance_booking_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='أيام الحجز المسبق'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='awards',
            field=models.JSONField(blank=True, default=list, verbose_name='الجوائز'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='bar_available',
            field=models.BooleanField(default=False, verbose_name='بار متاح'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='booking_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الحجز'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='business_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الأعمال'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='cancellation_policy',
            field=models.TextField(blank=True, verbose_name='سياسة الإلغاء'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='certifications',
            field=models.JSONField(blank=True, default=list, verbose_name='الشهادات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الدخول'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت تسجيل الخروج'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='distance_to_attractions',
            field=models.JSONField(blank=True, default=dict, verbose_name='المسافة للمعالم'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='dress_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزي المطلوب'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='جهات اتصال الطوارئ'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='entertainment_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الترفيه'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='event_venues',
            field=models.JSONField(blank=True, default=list, verbose_name='قاعات المناسبات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='has_24_7_reception',
            field=models.BooleanField(default=False, verbose_name='استقبال 24/7'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='has_medical_services',
            field=models.BooleanField(default=False, verbose_name='خدمات طبية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='has_safety_certification',
            field=models.BooleanField(default=False, verbose_name='شهادة سلامة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='حراسة أمنية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='holiday_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='رسامة العطل'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='meal_options',
            field=models.JSONField(blank=True, default=list, verbose_name='خيارات الوجبات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='minimum_stay_days',
            field=models.IntegerField(blank=True, default=0, verbose_name='أقل مدة إقامة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='nearby_attractions',
            field=models.JSONField(blank=True, default=list, verbose_name='المعالم القريبة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='organized_activities',
            field=models.JSONField(blank=True, default=list, verbose_name='الأنشطة المنظمة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='طرق الدفع'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='provides_transportation',
            field=models.BooleanField(default=False, verbose_name='يقدم مواصلات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='restaurant_cuisine',
            field=models.JSONField(blank=True, default=list, verbose_name='مطاعم'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='room_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع الغرف'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='safety_measures',
            field=models.TextField(blank=True, verbose_name='إجراءات السلامة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='seasonal_pricing',
            field=models.JSONField(blank=True, default=dict, verbose_name='التسعير الموسمية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='services_additional',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات الإضافية'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='services_cost',
            field=models.JSONField(blank=True, default=dict, verbose_name='تكلفة الخدمات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='services_included',
            field=models.JSONField(blank=True, default=list, verbose_name='الخدمات المشمولة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='smoking_policy',
            field=models.CharField(blank=True, max_length=50, verbose_name='سياسة التدخين'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='sports_facilities',
            field=models.JSONField(blank=True, default=list, verbose_name='مرافق الرياضة'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='suite_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع السويت'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='هاتف الدعم'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='transportation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة المواصلات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='transportation_types',
            field=models.JSONField(blank=True, default=list, verbose_name='أنواع المواصلات'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='resortoutsideiraq',
            name='weekend_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='رسامة عطلة نهاية الأسبوع'),
        ),
    ]
