# Generated by Django 5.2.17 on 2026-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0158_resortinsideiraq_accepts_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='property',
            name='appreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='معدل النمو'),
        ),
        migrations.AddField(
            model_name='property',
            name='crime_rate',
            field=models.CharField(blank=True, max_length=50, verbose_name='معدل الجريمة'),
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مبلغ التأمين'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='مزود الكهرباء'),
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_efficiency_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='درجة كفاءة الطاقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, max_length=10, verbose_name='تصنيف الطاقة'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعة المرآب'),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='مزيد الغاز'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_360_images',
            field=models.BooleanField(default=False, verbose_name='صور 360 درجة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_attic',
            field=models.BooleanField(default=False, verbose_name='علية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_basement',
            field=models.BooleanField(default=False, verbose_name='قبو'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_building_permit',
            field=models.BooleanField(default=False, verbose_name='رخصة بناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_carport',
            field=models.BooleanField(default=False, verbose_name='سقف سيارات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_deck',
            field=models.BooleanField(default=False, verbose_name='سطح خشبي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator_access',
            field=models.BooleanField(default=False, verbose_name='وصول للمصعد'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_geothermal',
            field=models.BooleanField(default=False, verbose_name='طاقة جوفية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_handrails',
            field=models.BooleanField(default=False, verbose_name='أدراج يدوية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_irrigation_system',
            field=models.BooleanField(default=False, verbose_name='نظام ري'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outhouse',
            field=models.BooleanField(default=False, verbose_name='مبنى خارجي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_patio',
            field=models.BooleanField(default=False, verbose_name='فناء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_property_insurance',
            field=models.BooleanField(default=False, verbose_name='تأمين العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ramps',
            field=models.BooleanField(default=False, verbose_name='منحدرات'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_recent_renovations',
            field=models.BooleanField(default=False, verbose_name='تجديدات حديثة'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smart_lighting',
            field=models.BooleanField(default=False, verbose_name='إضاءة ذكية'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smart_security',
            field=models.BooleanField(default=False, verbose_name='أمان ذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smart_thermostat',
            field=models.BooleanField(default=False, verbose_name='منظم حرارة ذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_storage_room',
            field=models.BooleanField(default=False, verbose_name='غرفة تخزين'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_voice_control',
            field=models.BooleanField(default=False, verbose_name='تحكم صوتي'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_filtration',
            field=models.BooleanField(default=False, verbose_name='فلترة ماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_tank',
            field=models.BooleanField(default=False, verbose_name='خزان ماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_well',
            field=models.BooleanField(default=False, verbose_name='بئر ماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wind_turbine',
            field=models.BooleanField(default=False, verbose_name='توربينات رياح'),
        ),
        migrations.AddField(
            model_name='property',
            name='heritage_listed',
            field=models.BooleanField(default=False, verbose_name='مدرج في التراث'),
        ),
        migrations.AddField(
            model_name='property',
            name='historical_significance',
            field=models.TextField(blank=True, verbose_name='الأهمية التاريخية'),
        ),
        migrations.AddField(
            model_name='property',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التأمين'),
        ),
        migrations.AddField(
            model_name='property',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='شركة التأمين'),
        ),
        migrations.AddField(
            model_name='property',
            name='internet_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='مزيد الإنترنت'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='درجة الاستثمار'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_historical',
            field=models.BooleanField(default=False, verbose_name='عقار تاريخي'),
        ),
        migrations.AddField(
            model_name='property',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمات مفتاحية'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_term',
            field=models.CharField(blank=True, max_length=50, verbose_name='مدة العقد'),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_hospitals',
            field=models.JSONField(blank=True, default=list, verbose_name='المستشفيات القريبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_parks',
            field=models.JSONField(blank=True, default=list, verbose_name='الحدائق القريبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_schools',
            field=models.JSONField(blank=True, default=list, verbose_name='المدارس القريبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_shopping',
            field=models.JSONField(blank=True, default=list, verbose_name='مراكز التسوق القريبة'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='تقييم الحي'),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الرخصة'),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الرخصة'),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_restrictions',
            field=models.TextField(blank=True, verbose_name='قيود الحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='يسمح بالحيوانات الأليفة'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_documents',
            field=models.JSONField(blank=True, default=list, verbose_name='وثائق العقار'),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation_cost',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='تكلفة التجديد'),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_increase_terms',
            field=models.TextField(blank=True, verbose_name='شروط زيادة الإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_terms',
            field=models.TextField(blank=True, verbose_name='شروط الإيجار'),
        ),
        migrations.AddField(
            model_name='property',
            name='requires_appointment',
            field=models.BooleanField(default=False, verbose_name='يحتاج موعد'),
        ),
        migrations.AddField(
            model_name='property',
            name='smart_home_features',
            field=models.JSONField(blank=True, default=list, verbose_name='ميزات المنزل الذكي'),
        ),
        migrations.AddField(
            model_name='property',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=100, verbose_name='سعة التخزين'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_document',
            field=models.FileField(blank=True, null=True, upload_to='property_documents/', verbose_name='وثيقة الطابو'),
        ),
        migrations.AddField(
            model_name='property',
            name='utility_costs',
            field=models.JSONField(blank=True, default=dict, verbose_name='تكاليف الخدمات'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
        migrations.AddField(
            model_name='property',
            name='viewing_availability',
            field=models.JSONField(blank=True, default=dict, verbose_name='أوقات المعاينة'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_viewing_available',
            field=models.BooleanField(default=False, verbose_name='معاينة افتراضية متاحة'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='مزيد الماء'),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
    ]
