# Generated by Django 5.2.17 on 2026-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0160_sitesettings_access_log_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='additional_services',
            field=models.JSONField(default=list, verbose_name='الخدمات الإضافية المطلوبة'),
        ),
    ]
