# Generated by Django 5.2.17 on 2026-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0161_subscriptionrenewalrequest_additional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='subscription_types',
            field=models.JSONField(default=list, verbose_name='أنواع الاشتراكات المطلوبة'),
        ),
    ]
