# Generated by Django 5.2.17 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0162_subscriptionrenewalrequest_subscription_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='التجديد التلقائي'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='notify_sms',
            field=models.BooleanField(default=False, verbose_name='إشعارات الرسائل النصية'),
        ),
        migrations.AddField(
            model_name='subscriptionrenewalrequest',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'المحفظة الإلكترونية'), ('bank', 'التحويل البنكي'), ('cash', 'الدفع النقدي')], default='wallet', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='subscriptionrenewalrequest',
            name='additional_services',
            field=models.JSONField(default=list, verbose_name='الخدمات الإضافية'),
        ),
        migrations.AlterField(
            model_name='subscriptionrenewalrequest',
            name='subscription_types',
            field=models.JSONField(default=list, verbose_name='أنواع الاشتراكات'),
        ),
    ]
