# Generated by Django 5.2.17 on 2026-08-13 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0163_subscriptionrenewalrequest_auto_renewal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('user', 'مستخدم'), ('property', 'عقار'), ('conversation', 'محادثة'), ('broker', 'دلال')], max_length=20, verbose_name='نوع التقييم')),
                ('target_id', models.IntegerField(verbose_name='معرف الهدف')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المراجعة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.rating', verbose_name='التقييم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('property_viewing', 'معاينة عقار'), ('phone_call', 'مكالمة هاتفية'), ('meeting', 'اجتماع'), ('video_call', 'مكالمة فيديو')], max_length=30, verbose_name='نوع الموعد')),
                ('target_id', models.IntegerField(verbose_name='معرف الهدف')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'indexes': [models.Index(fields=['user', 'appointment_date', 'appointment_time'], name='properties__user_id_7abf91_idx'), models.Index(fields=['status', 'appointment_date'], name='properties__status_6cfa63_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating_type', 'target_id'], name='properties__rating__570002_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_6d6bc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'rating_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', '-created_at'], name='properties__rating__90cebc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='properties__user_id_a86832_idx'),
        ),
    ]
