# Generated by Django 5.2.17 on 2026-08-14 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0164_rating_review_appointment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_matches', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني للمطابقات الجديدة')),
                ('email_new_responses', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني للردود الجديدة')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='إشعارات التطبيق')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='إشعارات SMS')),
                ('notification_frequency', models.CharField(choices=[('instant', 'فوري'), ('hourly', 'كل ساعة'), ('daily', 'يوميا'), ('weekly', 'أسبوعيا')], default='instant', max_length=20, verbose_name='تكرار الإشعارات')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية ساعات الصمت')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية ساعات الصمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات إشعارات الإعلانات',
                'verbose_name_plural': 'إعدادات إشعارات الإعلانات',
            },
        ),
        migrations.CreateModel(
            name='BuildingAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('project_type', models.CharField(max_length=50, verbose_name='نوع المشروع')),
                ('property_type', models.CharField(choices=[('house', 'بيت'), ('apartment', 'شقة'), ('villa', 'فيلا'), ('building', 'بناية'), ('commercial', 'تجاري')], max_length=20, verbose_name='نوع العقار المطلوب')),
                ('governorate', models.CharField(choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=10, verbose_name='المحافظة المفضلة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='القضاء')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('min_budget', models.BigIntegerField(verbose_name='الحد الأدنى للميزانية')),
                ('max_budget', models.BigIntegerField(verbose_name='الحد الأقصى للميزانية')),
                ('estimated_area', models.IntegerField(verbose_name='المساحة المقدرة (م²)')),
                ('timeline_months', models.IntegerField(verbose_name='المدة المتوقعة (أشهر)')),
                ('ad_type', models.CharField(choices=[('general', 'عام'), ('specific', 'محدد'), ('urgent', 'عاجل')], default='general', max_length=20, verbose_name='نوع الإعلان')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('completed', 'مكتمل'), ('expired', 'منتهي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('target_contractors', models.BooleanField(default=True, verbose_name='استهداف المقاولين')),
                ('target_property_owners', models.BooleanField(default=True, verbose_name='استهداف ملاك العقارات')),
                ('target_building_companies', models.BooleanField(default=True, verbose_name='استهداف شركات البناء')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'هاتف'), ('email', 'بريد إلكتروني'), ('both', 'كلاهما')], default='both', max_length=20, verbose_name='طريقة التواصل المفضلة')),
                ('is_public', models.BooleanField(default=True, verbose_name='عرض للجمهور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('responses_count', models.IntegerField(default=0, verbose_name='عدد الردود')),
                ('matched_count', models.IntegerField(default=0, verbose_name='عدد المطابقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_ads', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعلان بناء',
                'verbose_name_plural': 'إعلانات البناء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('quote', 'عرض سعر'), ('inquiry', 'استفسار'), ('proposal', 'اقتراح'), ('meeting', 'طلب اجتماع')], max_length=20, verbose_name='نوع الرد')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('message', models.TextField(verbose_name='رسالة الرد')),
                ('proposed_price', models.BigIntegerField(blank=True, null=True, verbose_name='السعر المقترح')),
                ('proposed_timeline', models.IntegerField(blank=True, null=True, verbose_name='المدة المقترحة (أشهر)')),
                ('preferred_meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاجتماع المفضل')),
                ('meeting_location', models.CharField(blank=True, max_length=200, verbose_name='موقع الاجتماع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('attached_files', models.ManyToManyField(blank=True, to='properties.propertydocument', verbose_name='الملفات المرفقة')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_responses', to=settings.AUTH_USER_MODEL, verbose_name='المجيب')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='properties.buildingadvertisement', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'رد على إعلان',
                'verbose_name_plural': 'الردود على الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(choices=[(0, 'لا يوجد تطابق'), (1, 'تطابق ضعيف'), (2, 'تطابق متوسط'), (3, 'تطابق قوي'), (4, 'تطابق ممتاز'), (5, 'تطابق مثالي')], default=0, verbose_name='درجة التطابق')),
                ('match_reasons', models.JSONField(default=dict, verbose_name='أسباب التطابق')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='تمت المشاهدة')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='تم التواصل')),
                ('is_converted', models.BooleanField(default=False, verbose_name='تم التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('matched_broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_matches', to='properties.broker', verbose_name='الدلال المطابق')),
                ('matched_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_matches', to='properties.property', verbose_name='العقار المطابق')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_matches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المطابق')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='properties.buildingadvertisement', verbose_name='الإعلان')),
            ],
            options={
                'verbose_name': 'مطابقة إعلان',
                'verbose_name_plural': 'مطابقات الإعلانات',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
