# Generated by Django 5.2.17 on 2026-08-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0166_alter_channelanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelanalytics',
            options={'verbose_name': 'إحصائيات قناة', 'verbose_name_plural': 'إحصائيات القنوات'},
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='average_content_engagement',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='average_session_duration',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='booking_conversions',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='bounce_rate',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='desktop_users',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='facebook_referrals',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='instagram_referrals',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='last_analyzed',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='lead_conversions',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='mobile_users',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='monthly_growth_rate',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='pages_per_session',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='peak_days',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='peak_hours',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='property_inquiries',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='returning_visitors',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='tablet_users',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='telegram_referrals',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='top_cities',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='top_governorates',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='total_content_views',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='total_visitors',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='unique_visitors',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='weekly_growth_rate',
        ),
        migrations.RemoveField(
            model_name='channelanalytics',
            name='whatsapp_referrals',
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='متوسط التقييم'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='average_response_time',
            field=models.PositiveIntegerField(default=0, verbose_name='متوسط وقت الرد (دقيقة)'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة التحويل'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='daily_followers',
            field=models.JSONField(blank=True, default=dict, verbose_name='المتابعين اليوميين'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='daily_views',
            field=models.JSONField(blank=True, default=dict, verbose_name='المشاهدات اليومية'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='monthly_followers',
            field=models.JSONField(blank=True, default=dict, verbose_name='المتابعين الشهريين'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='monthly_views',
            field=models.JSONField(blank=True, default=dict, verbose_name='المشاهدات الشهرية'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='properties_contacted',
            field=models.PositiveIntegerField(default=0, verbose_name='عقارات تم التواصل بشأنها'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='properties_viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='عقارات تمت مشاهدتها'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='response_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الرد'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي المراجعات'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='total_saves',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الحفظ'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='total_shares',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي المشاركات'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='weekly_followers',
            field=models.JSONField(blank=True, default=dict, verbose_name='المتابعين الأسبوعيين'),
        ),
        migrations.AddField(
            model_name='channelanalytics',
            name='weekly_views',
            field=models.JSONField(blank=True, default=dict, verbose_name='المشاهدات الأسبوعية'),
        ),
        migrations.CreateModel(
            name='ChannelAnalyticsAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0, verbose_name='إجمالي الزوار')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='الزوار الفريدين')),
                ('returning_visitors', models.PositiveIntegerField(default=0, verbose_name='الزوار العائدين')),
                ('average_session_duration', models.PositiveIntegerField(default=0, verbose_name='متوسط مدة الجلسة (ثانية)')),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='معدل الارتداد')),
                ('pages_per_session', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='الصفحات لكل جلسة')),
                ('total_content_views', models.PositiveIntegerField(default=0, verbose_name='إجمالي مشاهدات المحتوى')),
                ('average_content_engagement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='متوسط تفاعل المحتوى')),
                ('lead_conversions', models.PositiveIntegerField(default=0, verbose_name='تحويلات العملاء المحتملين')),
                ('property_inquiries', models.PositiveIntegerField(default=0, verbose_name='استفسارات العقارات')),
                ('booking_conversions', models.PositiveIntegerField(default=0, verbose_name='تحويلات الحجز')),
                ('top_governorates', models.JSONField(default=dict, verbose_name='أهم المحافظات')),
                ('top_cities', models.JSONField(default=dict, verbose_name='أهم المدن')),
                ('desktop_users', models.PositiveIntegerField(default=0, verbose_name='مستخدمي سطح المكتب')),
                ('mobile_users', models.PositiveIntegerField(default=0, verbose_name='مستخدمي الجوال')),
                ('tablet_users', models.PositiveIntegerField(default=0, verbose_name='مستخدمي الأجهزة اللوحية')),
                ('peak_hours', models.JSONField(default=dict, verbose_name='ساعات الذروة')),
                ('peak_days', models.JSONField(default=dict, verbose_name='أيام الذروة')),
                ('facebook_referrals', models.PositiveIntegerField(default=0, verbose_name='إحالات فيسبوك')),
                ('instagram_referrals', models.PositiveIntegerField(default=0, verbose_name='إحالات انستغرام')),
                ('whatsapp_referrals', models.PositiveIntegerField(default=0, verbose_name='إحالات واتساب')),
                ('telegram_referrals', models.PositiveIntegerField(default=0, verbose_name='إحالات تيليجرام')),
                ('weekly_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='معدل النمو الأسبوعي')),
                ('monthly_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='معدل النمو الشهري')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='آخر تحليل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_advanced', to='properties.brokerchannel', verbose_name='القناة')),
            ],
            options={
                'verbose_name': 'تحليلات قناة',
                'verbose_name_plural': 'تحليلات القنوات',
            },
        ),
    ]
