# Generated by Django 5.2.17 on 2026-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0167_alter_channelanalytics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerchannel',
            name='category',
            field=models.CharField(choices=[('properties_iraq', '🏠 عقارات داخل العراق'), ('properties_foreign', '🌍 عقارات خارج العراق'), ('hotels_iraq', '🏨🇮🇶 فنادق داخل العراق'), ('hotels_foreign', '🏨🌍 فنادق خارج العراق'), ('resorts_iraq', '🏝️🇮🇶 منتجعات داخل العراق'), ('resorts_foreign', '🏝️🌍 منتجعات خارج العراق'), ('travel_agency', '✈️ شركة سفر'), ('jobs', '➕ وظائف'), ('building_requests', '🏗️ طلبات بناء'), ('services', '🔧 خدمات'), ('auctions', '🔨 مزادات')], default='properties_iraq', max_length=30, verbose_name='تصنيف القناة'),
        ),
        migrations.AddIndex(
            model_name='brokerchannel',
            index=models.Index(fields=['category'], name='properties__categor_13c661_idx'),
        ),
    ]
