# Generated by Django 5.2.17 on 2026-08-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0169_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
    ]
