# Generated by Django 5.2.17 on 2026-08-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0170_supportmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='services_offered',
            field=models.JSONField(blank=True, default=list, help_text='قائمة الخدمات التي يقدمها الدلال مثل: بيع، شراء، إيجار، استثمار، تأجير، مبيعات، إلخ', verbose_name='الخدمات المقدمة'),
        ),
        migrations.AddField(
            model_name='broker',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text='تخصصات الدلال مثل: سكني، تجاري، صناعي، زراعي، إلخ', verbose_name='التخصصات'),
        ),
    ]
