# Generated by Django 5.2.17 on 2026-08-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_ai_training_system'),
        ('properties', '0171_broker_services_offered_broker_specialties'),
    ]

    operations = [
    ]
