# Generated by Django 5.2.17 on 2026-08-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0173_voiceinteractionlog_alter_conversationlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, verbose_name='التوقيع الرقمي'),
        ),
        migrations.AddField(
            model_name='backup',
            name='database_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حجم قاعدة البيانات (MB)'),
        ),
        migrations.AddField(
            model_name='backup',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='مدة الإنشاء (ثواني)'),
        ),
        migrations.AddField(
            model_name='backup',
            name='file_count',
            field=models.IntegerField(default=0, verbose_name='عدد الملفات'),
        ),
        migrations.AddField(
            model_name='backup',
            name='is_protected',
            field=models.BooleanField(default=False, verbose_name='محمية'),
        ),
        migrations.AddField(
            model_name='backup',
            name='is_safety_backup',
            field=models.BooleanField(default=False, verbose_name='نسخة أمان'),
        ),
        migrations.AddField(
            model_name='backup',
            name='media_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حجم الملفات (MB)'),
        ),
        migrations.AddField(
            model_name='backup',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستعادة'),
        ),
        migrations.AddField(
            model_name='backup',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الاستعادة بواسطة'),
        ),
        migrations.AddField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('queued', 'قيد الانتظار'), ('creating', 'قيد الإنشاء'), ('processing', 'قيد المعالجة'), ('completed', 'مكتملة'), ('failed', 'فشلت'), ('corrupted', 'تالفة'), ('restoring', 'قيد الاستعادة'), ('restored', 'مستعادة'), ('deleted', 'محذوفة')], default='queued', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='backup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='backup',
            name='version',
            field=models.CharField(default='v1', max_length=50, verbose_name='الإصدار'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'نسخة كاملة'), ('database', 'قاعدة البيانات'), ('files', 'الملفات'), ('custom', 'مخصصة')], max_length=20, verbose_name='نوع النسخة'),
        ),
        migrations.CreateModel(
            name='BackupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء نسخة'), ('saved', 'حفظ نسخة'), ('verified', 'فحص نسخة'), ('downloaded', 'تنزيل نسخة'), ('restored', 'استعادة نسخة'), ('deleted', 'حذف نسخة'), ('protected', 'حماية نسخة'), ('failed', 'فشل عملية')], max_length=20, verbose_name='العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('result', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل')], max_length=20, verbose_name='النتيجة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='properties.backup', verbose_name='النسخة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل عمليات النسخ',
                'verbose_name_plural': 'سجلات عمليات النسخ',
                'ordering': ['-created_at'],
            },
        ),
    ]
