# Generated by Django 5.2.17 on 2026-08-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0174_backup_checksum_backup_database_size_backup_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrequest',
            name='target_service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_building_requests', to='properties.serviceprovider', verbose_name='مقدم الخدمة المستهدف'),
        ),
    ]
