# Generated by Django 5.2.17 on 2026-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0175_buildingrequest_target_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, verbose_name='صور إضافية'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='رابط الفيديو'),
        ),
    ]
