# Generated by Django 5.2.17 on 2026-08-17 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0176_serviceprovider_additional_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='معرف المحادثة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conversations', to='properties.broker', verbose_name='الدلال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_conversations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة دلال',
                'verbose_name_plural': 'محادثات الدلالين',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('image', 'صورة'), ('file', 'ملف'), ('location', 'موقع'), ('property', 'عقار')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('content', models.TextField(blank=True, verbose_name='محتوى الرسالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='broker_messages/images/', verbose_name='صورة')),
                ('file', models.FileField(blank=True, null=True, upload_to='broker_messages/files/', verbose_name='ملف')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.brokerconversation', verbose_name='المحادثة')),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_references', to='properties.property', verbose_name='العقار المرجعي')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_broker_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستقبل')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة دلال',
                'verbose_name_plural': 'رسائل الدلالين',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brokerconversation',
            index=models.Index(fields=['conversation_id'], name='properties__convers_8ecbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconversation',
            index=models.Index(fields=['user', '-last_message_at'], name='properties__user_id_f07d19_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconversation',
            index=models.Index(fields=['broker', '-last_message_at'], name='properties__broker__02d956_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerconversation',
            index=models.Index(fields=['expires_at'], name='properties__expires_a9d99f_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['conversation', '-created_at'], name='properties__convers_552c30_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['sender', '-created_at'], name='properties__sender__34c0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['receiver', '-created_at'], name='properties__receive_f12d82_idx'),
        ),
        migrations.AddIndex(
            model_name='brokermessage',
            index=models.Index(fields=['is_read'], name='properties__is_read_546712_idx'),
        ),
    ]
