# Generated by Django 5.2.17 on 2026-08-17 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0177_brokerconversation_brokermessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('desktop', 'حاسوب'), ('mobile', 'هاتف'), ('tablet', 'جهاز لوحي'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الجهاز')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='المتصفح')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار المتصفح')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='نظام التشغيل')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='إصدار نظام التشغيل')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_current', models.BooleanField(default=False, verbose_name='الجهاز الحالي')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تسجيل الدخول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز مستخدم',
                'verbose_name_plural': 'أجهزة المستخدمين',
                'ordering': ['-last_seen', '-login_at'],
                'indexes': [models.Index(fields=['user', '-last_seen'], name='properties__user_id_c58570_idx'), models.Index(fields=['user', 'is_active'], name='properties__user_id_6639e6_idx')],
            },
        ),
    ]
