# Generated by Django 5.2.17 on 2026-08-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0179_message_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/%Y/%m/%d/', verbose_name='الملف'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الملف'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)'),
        ),
    ]
