# Generated by Django 5.2.17 on 2026-08-17 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0180_message_file_message_file_name_message_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='alley',
            field=models.CharField(blank=True, help_text='اسم الزقاق', max_length=100, null=True, verbose_name='الزقاق'),
        ),
        migrations.AddField(
            model_name='property',
            name='block',
            field=models.CharField(blank=True, help_text='رقم البلوك', max_length=50, null=True, verbose_name='البلوك'),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, help_text='رقم الدار (يدعم أرقام وأحرف مثل: 12, 12A, 12/1)', max_length=50, null=True, verbose_name='رقم الدار'),
        ),
        migrations.AddField(
            model_name='property',
            name='mahalla',
            field=models.CharField(blank=True, help_text='رقم أو اسم المحلة', max_length=100, null=True, verbose_name='المحلة'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['mahalla'], name='properties__mahalla_22019d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['block'], name='properties__block_9ffe84_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['alley'], name='properties__alley_e20e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['house_number'], name='properties__house_n_ea5f21_idx'),
        ),
    ]
