# Generated by Django 5.2.17 on 2026-08-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0181_property_alley_property_block_property_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='properties__mahalla_22019d_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__block_9ffe84_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__alley_e20e0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='properties__house_n_ea5f21_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي التفصيلي'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_plot_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='alley',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الزقاق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='البلوك'),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المحلة'),
        ),
    ]
