# Generated by Django 5.2.17 on 2026-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0182_remove_property_properties__mahalla_22019d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مساحة القطعة (م²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='polygon_coordinates',
            field=models.JSONField(blank=True, help_text='إحداثيات حدود قطعة الأرض بصيغة GeoJSON', null=True, verbose_name='حدود العقار (Polygon)'),
        ),
    ]
