# Generated by Django 5.2.17 on 2026-08-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0183_property_plot_area_property_polygon_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceadvertisement',
            name='alley',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزقاق'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='block',
            field=models.CharField(blank=True, max_length=50, verbose_name='البلوك'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الدار'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحلة'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='property_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العقار'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشارع'),
        ),
        migrations.AddField(
            model_name='serviceadvertisement',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, verbose_name='الناحية'),
        ),
    ]
