# Generated by Django 5.2.17 on 2026-08-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0184_serviceadvertisement_alley_serviceadvertisement_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='alley',
            field=models.CharField(blank=True, max_length=100, verbose_name='الزقاق'),
        ),
        migrations.AddField(
            model_name='auction',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='auction',
            name='block',
            field=models.CharField(blank=True, max_length=50, verbose_name='البلوك'),
        ),
        migrations.AddField(
            model_name='auction',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='auction',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='القضاء'),
        ),
        migrations.AddField(
            model_name='auction',
            name='governorate',
            field=models.CharField(blank=True, choices=[('BAG', 'بغداد'), ('BAS', 'البصرة'), ('NIN', 'نينوى'), ('ERB', 'أربيل'), ('NAJ', 'النجف'), ('KAR', 'كربلاء'), ('BAB', 'بابل'), ('DHI', 'ذي قار'), ('DIA', 'ديالى'), ('KIR', 'كركوك'), ('ANB', 'الأنبار'), ('WAS', 'واسط'), ('MUT', 'ميسان'), ('MUTH', 'المثنى'), ('QAD', 'القادسية (الديوانية)'), ('SAL', 'صلاح الدين'), ('DUH', 'دهوك'), ('SUL', 'السليمانية'), ('HAL', 'حلبجة')], max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='auction',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الدار'),
        ),
        migrations.AddField(
            model_name='auction',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, verbose_name='أقرب نقطة دالة'),
        ),
        migrations.AddField(
            model_name='auction',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100, verbose_name='المحلة'),
        ),
        migrations.AddField(
            model_name='auction',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='auction',
            name='property_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العقار'),
        ),
        migrations.AddField(
            model_name='auction',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشارع'),
        ),
        migrations.AddField(
            model_name='auction',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, verbose_name='الناحية'),
        ),
    ]
