# Generated by Django 5.2.17 on 2026-08-18 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0185_auction_alley_auction_area_auction_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('property_viewing', 'معاينة عقار'), ('phone_call', 'مكالمة هاتفية'), ('meeting', 'اجتماع'), ('video_call', 'مكالمة فيديو'), ('office_visit', 'زيارة المكتب')], max_length=30, verbose_name='نوع الموعد')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('duration', models.IntegerField(default=30, verbose_name='المدة (دقائق)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('broker_notes', models.TextField(blank=True, verbose_name='ملاحظات الدلال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='تم إرسال التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='properties__user_id_7abf91_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='properties__status_6cfa63_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.broker', verbose_name='الدلال'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_appointments', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='brokerappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_appointments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='brokerappointment',
            index=models.Index(fields=['user', 'appointment_date', 'appointment_time'], name='properties__user_id_672cab_idx'),
        ),
        migrations.AddIndex(
            model_name='brokerappointment',
            index=models.Index(fields=['status', 'appointment_date'], name='properties__status_c012e7_idx'),
        ),
    ]
