# Generated by Django 5.2.17 on 2026-08-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0186_brokerappointment_alter_appointment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('sale', 'عقد بيع'), ('rent', 'عقد إيجار'), ('lease', 'عقد تأجير'), ('agency', 'عقد وساطة'), ('management', 'عقد إدارة'), ('partnership', 'عقد شراكة'), ('maintenance', 'عقد صيانة'), ('other', 'عقد آخر')], max_length=20, verbose_name='نوع العقد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('active', 'نشط'), ('completed', 'مكتمل'), ('terminated', 'منهي'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('second_party_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الطرف الثاني')),
                ('second_party_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف الطرف الثاني')),
                ('second_party_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الطرف الثاني')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قيمة العقد')),
                ('deposit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='العربون')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة (%)')),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قيمة العمولة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('payment_frequency', models.CharField(choices=[('one_time', 'دفعة واحدة'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('annually', 'سنوي'), ('custom', 'مخصص')], default='one_time', max_length=20, verbose_name='تكرار الدفع')),
                ('payment_terms', models.TextField(blank=True, verbose_name='شروط الدفع')),
                ('terms_and_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('special_clauses', models.TextField(blank=True, verbose_name='البنود الخاصة')),
                ('renewal_clause', models.BooleanField(default=False, verbose_name='بند التجديد')),
                ('termination_clause', models.TextField(blank=True, verbose_name='بند الإنهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='properties.broker', verbose_name='الدلال')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'عقد عقاري',
                'verbose_name_plural': 'العقود العقارية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('renewal', 'تجديد'), ('expiration', 'انتهاء'), ('payment', 'دفعة'), ('inspection', 'فحص'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التذكير')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التذكير')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reminder_date', models.DateField(verbose_name='تاريخ التذكير')),
                ('reminder_days_before', models.IntegerField(default=7, verbose_name='أيام قبل التذكير')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.realestatecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'تذكير عقد',
                'verbose_name_plural': 'تذكيرات العقود',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, verbose_name='رقم الدفعة')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('partial', 'مدفوع جزئياً'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك'), ('card', 'بطاقة'), ('online', 'دفع إلكتروني')], max_length=20, verbose_name='طريقة الدفع')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contract_payments/', verbose_name='إيصال الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.realestatecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'دفعة عقد',
                'verbose_name_plural': 'مدفوعات العقود',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'العقد الأصلي'), ('addendum', 'مذكرة إضافة'), ('amendment', 'تعديل'), ('receipt', 'إيصال'), ('invoice', 'فاتورة'), ('id_copy', 'صورة الهوية'), ('property_docs', 'وثائق العقار'), ('other', 'وثيقة أخرى')], max_length=20, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوثيقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='contract_documents/', verbose_name='الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.realestatecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'وثيقة عقد',
                'verbose_name_plural': 'وثائق العقود',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['contract_number'], name='properties__contrac_3a1fae_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['status'], name='properties__status_be57ce_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['contract_type'], name='properties__contrac_18fa07_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['start_date', 'end_date'], name='properties__start_d_9e7b87_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatecontract',
            index=models.Index(fields=['-created_at'], name='properties__created_29a06d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreminder',
            index=models.Index(fields=['contract', 'reminder_date'], name='properties__contrac_e1be64_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreminder',
            index=models.Index(fields=['is_sent'], name='properties__is_sent_3e85b8_idx'),
        ),
        migrations.AddIndex(
            model_name='contractreminder',
            index=models.Index(fields=['reminder_date'], name='properties__reminde_1c754e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['contract', 'due_date'], name='properties__contrac_f4ba36_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['status'], name='properties__status_dde4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['-created_at'], name='properties__created_ef700d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['contract', 'document_type'], name='properties__contrac_06c5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['-uploaded_at'], name='properties__uploade_c54fa5_idx'),
        ),
    ]
