# Generated by Django 5.2.17 on 2026-08-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0187_realestatecontract_contractreminder_contractpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelcompany',
            name='booking_methods',
            field=models.JSONField(default=dict, help_text='طرق الحجز المتاحة', verbose_name='طرق الحجز'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='branch_locations',
            field=models.JSONField(default=dict, help_text='مواقع الفروع بالتفصيل', verbose_name='مواقع الفروع'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='certifications',
            field=models.JSONField(default=dict, verbose_name='الشهادات والاعتمادات'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='destinations',
            field=models.JSONField(default=dict, help_text='قائمة الوجهات التي تخدمها الشركة', verbose_name='الوجهات'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='facilities',
            field=models.JSONField(default=dict, help_text='المرافق المتوفرة مثل الحافلات، الفنادق، إلخ', verbose_name='المرافق'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='partners',
            field=models.JSONField(default=dict, verbose_name='الشركاء'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='services',
            field=models.JSONField(default=dict, help_text='الخدمات الإضافية مثل التأشيرات، الحجوزات، إلخ', verbose_name='الخدمات'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='special_offers',
            field=models.JSONField(default=dict, verbose_name='العروض الخاصة'),
        ),
        migrations.AlterField(
            model_name='travelcompany',
            name='travel_types',
            field=models.JSONField(default=dict, verbose_name='أنواع السفر المدعومة'),
        ),
    ]
