# Generated by Django 5.2.17 on 2026-08-24 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0188_alter_travelcompany_booking_methods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الرحلة')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان الرحلة بالإنجليزية')),
                ('description', models.TextField(verbose_name='وصف الرحلة')),
                ('description_en', models.TextField(blank=True, verbose_name='وصف الرحلة بالإنجليزية')),
                ('travel_type', models.CharField(choices=[('domestic', 'داخلي'), ('international', 'دولي'), ('hajj', 'حج'), ('umrah', 'عمرة'), ('tourism', 'سياحة'), ('business', 'أعمال'), ('adventure', 'مغامرة'), ('medical', 'علاجي'), ('educational', 'تعليمي'), ('family', 'عائلي'), ('luxury', 'فاخر'), ('budget', 'اقتصادي')], default='tourism', max_length=20, verbose_name='نوع الرحلة')),
                ('destination', models.CharField(max_length=200, verbose_name='الوجهة')),
                ('destination_en', models.CharField(blank=True, max_length=200, verbose_name='الوجهة بالإنجليزية')),
                ('duration_days', models.IntegerField(verbose_name='مدة الرحلة بالأيام')),
                ('duration_nights', models.IntegerField(default=0, verbose_name='عدد الليالي')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('price_currency', models.CharField(default='IQD', max_length=10, verbose_name='عملة السعر')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر الخصم')),
                ('max_participants', models.IntegerField(verbose_name='الحد الأقصى للمشاركين')),
                ('current_participants', models.IntegerField(default=0, verbose_name='عدد المشاركين الحالي')),
                ('departure_date', models.DateTimeField(verbose_name='تاريخ الانطلاق')),
                ('return_date', models.DateTimeField(verbose_name='تاريخ العودة')),
                ('booking_deadline', models.DateTimeField(verbose_name='موعد انتهاء الحجز')),
                ('inclusions', models.JSONField(default=dict, verbose_name='ما يشمله العرض')),
                ('exclusions', models.JSONField(default=dict, verbose_name='ما لا يشمله العرض')),
                ('itinerary', models.JSONField(default=dict, verbose_name='البرنامج الزمني')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='travel_packages/', verbose_name='صورة الغلاف')),
                ('gallery', models.JSONField(default=dict, verbose_name='معرض الصور')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('fully_booked', 'محجوز بالكامل'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='وصف SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_packages', to='properties.travelcompany', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'رحلة سفر',
                'verbose_name_plural': 'رحلات السفر',
                'ordering': ['-departure_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('adults_count', models.IntegerField(default=1, verbose_name='عدد البالغين')),
                ('children_count', models.IntegerField(default=0, verbose_name='عدد الأطفال')),
                ('special_requirements', models.TextField(blank=True, verbose_name='متطلبات خاصة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('paid', 'مدفوع'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.travelpackage', verbose_name='الرحلة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حجز رحلة',
                'verbose_name_plural': 'حجوزات الرحلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_packages/images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.travelpackage', verbose_name='الرحلة')),
            ],
            options={
                'verbose_name': 'صورة رحلة',
                'verbose_name_plural': 'صور الرحلات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم العام')),
                ('service_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='جودة الخدمة')),
                ('value_for_money', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='القيمة مقابل السعر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقييم')),
                ('comment', models.TextField(verbose_name='تعليق التقييم')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.travelpackage', verbose_name='الرحلة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_package_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم رحلة',
                'verbose_name_plural': 'تقييمات الرحلات',
                'ordering': ['-created_at'],
                'unique_together': {('package', 'user')},
            },
        ),
    ]
